Route102_Text_CalvinIntro: @ 8294513
	.string "You wanna fight me, Timmy?$"

Route102_Text_CalvinDefeated: @ 829457C
	.string "Man, maybe I was the Timmy…$"

Route102_Text_CalvinPostBattle: @ 82945AC
	.string "Man, maybe I was the Timmy…$"

Route102_Text_CalvinRegister: @ 82945EB
	.string "I've been working hard at this since\n"
	.string "I saw you before.\p"
	.string "I'd like to battle you again, so can\n"
	.string "you register me in your PokéNav?$"

Route102_Text_CalvinRegisterShort: @ 8294668
	.string "I'd like to battle you again, so can\n"
	.string "you register me in your PokéNav?$"

Route102_Text_CalvinRematchIntro: @ 82946AE
	.string "Anyone wanna battle a beginner? >///<$"

Route102_Text_CalvinRematchDefeated: @ 829470C
	.string "Arrgh, I lost… >-<$"

Route102_Text_CalvinRematchPostBattle: @ 829473C
	.string "Arrgh, I lost…$"

Route102_Text_AllenIntro: @ 8294775
	.string "So, you're new here huh? I'm rather\n"
	.string "new too, want to battle?$"

Route102_Text_AllenDefeated: @ 82947AA
	.string "Hmph, you got lucky. Well, this\n"
	.string "girl's gonna dip, see you around.$"

Route102_Text_AllenPostBattle: @ 82947DB
	.string "Hmph, you got lucky. Well, this\n"
	.string "girl's gonna dip, see you around.$"

Route102_Text_RickIntro: @ 829480C
	.string "My team will not surprise you.$"

Route102_Text_RickDefeated: @ 8294847
	.string "Is it the strongest team? No.\n"
	.string "Is it the most based? Yes.$"

Route102_Text_RickPostBattle: @ 8294859
	.string "Is it the strongest team? No.\n"
	.string "Is it the most based? Yes.$"

Route102_Text_TianaIntro: @ 829489E
	.string "Hey there, you look new. If you\n"
	.string "have any quwstions about battling lmk.\p"
	.string "Oh, you want to battle now?$"

Route102_Text_TianaDefeated: @ 82948F3
	.string "I might not have anything to teach you.$"

Route102_Text_TianaPostBattle: @ 8294916
	.string "I might not have anything to teach you.$"

Route103_Text_DaisyIntro: @ 829495A
	.string "Listening to Dragon Ball at the gym\n"
	.string "is what keeps me going.\p"
	.string "And gym girls.\p"
	.string "But mostly Dragon Ball.$"

Route103_Text_DaisyDefeated: @ 829498F
	.string "Damn, well things are still lookin\n"
	.string "up for ol Sand. A girl talked to me\p"
	.string "at the gym yesterday!$"

Route103_Text_DaisyPostBattle: @ 82949B4
	.string "She was like 'is anybody using this?'\n"
	.string "and I was like 'no'.$"

Route103_Text_AmyIntro: @ 82949F9
	.string "Amy: I'm AMY.\n"
	.string "And this is my little sister LIV.\l"
	.string "We battle together!$"

Route103_Text_AmyDefeated: @ 8294A3D
	.string "Amy: Uh-oh, we lost.$"

Route103_Text_AmyPostBattle: @ 8294A52
	.string "Amy: You have to think about all\n"
	.string "kinds of things when you're battling\l"
	.string "against two Trainers.$"

Route103_Text_AmyNotEnoughPokemon: @ 8294AAE
	.string "Amy: Uh-oh, you have only one\n"
	.string "Pokémon with you.\l"
	.string "You can't battle us like that.$"

Route103_Text_LivIntro: @ 8294AFD
	.string "Liv: We battle together as one\n"
	.string "team.$"

Route103_Text_LivDefeated: @ 8294B22
	.string "Liv: Oh, we lost, big sister…$"

Route103_Text_LivPostBattle: @ 8294B40
	.string "Liv: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But we still lost…$"

Route103_Text_AmyLivRegister: @ 8294B8A
	.string "Liv: Really, we're a lot better…\n"
	.string "It's true! We'll show you next time!$"

Route103_Text_LivNotEnoughPokemon: @ 8294BD0
	.string "Liv: If you want to battle us,\n"
	.string "you have to have two Pokémon!\l"
	.string "It's not fair if you don't!$"

Route103_Text_AmyRematchIntro: @ 8294C29
	.string "Amy: I'm Amy.\n"
	.string "And this is my little sister Liv.\l"
	.string "We battle together!$"

Route103_Text_AmyRematchDefeated: @ 8294C6D
	.string "Amy: Aww, boo!\n"
	.string "We couldn't win again…$"

Route103_Text_AmyRematchPostBattle: @ 8294C93
	.string "Amy: You have to think about all\n"
	.string "kinds of things when you're battling\l"
	.string "against two Trainers.$"

Route103_Text_AmyRematchNotEnoughPokemon: @ 8294CEF
	.string "Amy: Uh-oh, you have only one\n"
	.string "Pokémon with you.\l"
	.string "You can't battle us like that.$"

Route103_Text_LivRematchIntro: @ 8294D3E
	.string "Liv: We battle together as one\n"
	.string "team.$"

Route103_Text_LivRematchDefeated: @ 8294D63
	.string "Liv: Awww, we lost again…\n"
	.string "Big sister…$"

Route103_Text_LivRematchPostBattle: @ 8294D89
	.string "Liv: We work perfectly together,\n"
	.string "me and my big sister…\p"
	.string "But why did we lose again?$"

Route103_Text_LivRematchNotEnoughPokemon: @ 8294DDB
	.string "Liv: If you want to battle us, you\n"
	.string "have to have two Pokémon!\l"
	.string "It's not fair if you don't!$"

Route103_Text_AndrewIntro: @ 8294E34
	.string "Who's your favorite Fates character?\n"
	.string "Mine are Peri and Garon!\p"
	.string "…What do you mean I have bad taste?$"

Route103_Text_AndrewDefeated: @ 8294E92
	.string "Let's agree to disagree.$"

Route103_Text_AndrewPostBattle: @ 8294EBB
	.string "Let's agree to disagree.$"

Route103_Text_MiguelIntro: @ 8294EDF
	.string "Is Yashiro a good MC?$"

Route103_Text_MiguelDefeated: @ 8294F21
	.string "I can do Felix too.$"

Route103_Text_MiguelPostBattle: @ 8294F42
	.string "I can do Felix too.$"

Route103_Text_MiguelRegister: @ 8294F7E
	.string "I'll get you to come out and look in\n"
	.string "on my delightful Pokémon again!$"

Route103_Text_MiguelRematchIntro: @ 8294FC3
	.string "Hmm… I can't battle for too long,\n"
	.string "but we can do one real quick.$"

Route103_Text_MiguelRematchDefeated: @ 8295006
	.string "Yeah think I'm gonna go back to\n"
	.string "Genshin now.$"

Route103_Text_MiguelRematchPostBattle: @ 829501E
	.string "The more I spend time with it,\n"
	.string "the more adorable my Pokémon becomes.$"

Route103_Text_PeteIntro: @ 8295063
	.string "This sort of distance…\n"
	.string "You should just swim it!$"

Route103_Text_PeteDefeated: @ 8295093
	.string "Oh, that's good going!$"

Route103_Text_PetePostBattle: @ 82950AA
	.string "Oh, I understand where you're coming\n"
	.string "from now.\p"
	.string "If I had a Pokémon that trusty,\n"
	.string "I'd want to Surf on it, too!$"

Route103_Text_IsabelleIntro: @ 8295116
	.string "Watch where you're going!\n"
	.string "We're going to crash!$"

Route103_Text_IsabelleDefeated: @ 8295146
	.string "Groan…$"

Route103_Text_IsabellePostBattle: @ 829514D
	.string "I'm a poor swimmer so I was practicing…\n"
	.string "Sorry for almost crashing into you.$"

Route103_Text_RhettIntro: @ 8295199
	.string "Some day, I'm going to own all the\n"
	.string "Marth cards in Cipher!$"

Route103_Text_RhettDefeated: @ 82951C6
	.string "I needed that money to buy them…$"

Route103_Text_RhettPostBattle: @ 82951DE
	.string "I needed that money to buy them…$"

Route103_Text_MarcosIntro: @ 8295206
	.string "Hey there, wanna buy a box?$"

Route103_Text_MarcosDefeated: @ 829522B
	.string "No like a Cipher booster box.\n"
	.string "What did you think I meant?$"

Route103_Text_MarcosPostBattle: @ 8295246
	.string "No like a Cipher booster box.\n"
	.string "What did you think I meant?$"

Route104_Text_GinaIntro: @ 82952BB
	.string "Palafin not being in this game is lame.$"

Route104_Text_GinaDefeat: @ 82952E6
	.string "I would have won with Palafin…$"

Route104_Text_GinaPostBattle: @ 82952FE
	.string "Gina: You are strong!\n"
	.string "We have to train lots more!$"

Route104_Text_GinaNotEnoughMons: @ 8295330
	.string "Gina: Oh? Only one Pokémon?\n"
	.string "Then, we don't battle with you.\p"
	.string "If there's only one Pokémon, it will\n"
	.string "be lonesome. That's not nice.$"

Route104_Text_MiaIntro: @ 82953AF
	.string "Are you interesting in joining the\n"
	.string "Lissa Fan Club?$"

Route104_Text_MiaDefeat: @ 82953E1
	.string "Dang, I got excited when Luka joined…$"

Route104_Text_MiaPostBattle: @ 829540D
	.string "Dang, I got excited when Luka joined…$"

Route104_Text_MiaNotEnoughMons: @ 8295449
	.string "Mia: You want to battle with us?\p"
	.string "It's a big no-no if you don't have two\n"
	.string "Pokémon with you.\l"
	.string "We're too strong for you!$"

Route104_Text_IvanIntro: @ 82954BD
	.string "Sup, nerd.$"

Route104_Text_IvanDefeat: @ 8295509
	.string "Damn, I lost to YOU?$"

Route104_Text_IvanPostBattle: @ 829554E
	.string "I need to make my aggro team better.$"

Route104_Text_BillyIntro: @ 829558A
	.string "Hey, do you have any Camilla/Ashe\n"
	.string "fanart?$"

Route104_Text_BillyDefeat: @ 82955B4
	.string "I just think they're neat.$"

Route104_Text_BillyPostBattle: @ 82955E8
	.string "…What?$"

Route104_Text_HaleyIntro: @ 829563A
	.string "Been thinking about what Pokémon\n"
	.string "Leif would use…\p"
	.string "Anyway, let's do this.$"

Route104_Text_HaleyDefeat: @ 829566F
	.string "Leif would have won…$"

Route104_Text_HaleyPostBattle: @ 8295689
	.string "Leif would have won…$"

Route104_Text_HaleyRegister1: @ 82956FF
	.string "You're strong, but should I register\n"
	.string "you in my PokéNav?\l"
	.string "Maybe I shouldn't…\p"
	.string "Okay, sure, I will register you!$"

Route104_Text_HaleyRegister2: @ 829576B
	.string "You're strong, but should I register\n"
	.string "you in my PokéNav?\l"
	.string "Maybe I shouldn't…\p"
	.string "Okay, sure, I will register you!$"

Route104_Text_HaleyRematchIntro: @ 82957D7
	.string "Come on, battle with me!$"

Route104_Text_HaleyRematchDefeat: @ 82957F0
	.string "Ohh…\n"
	.string "I thought I could win…$"

Route104_Text_HaleyPostRematch: @ 829580C
	.string "I made the decision to battle, so\n"
	.string "I can accept this loss with grace.\p"
	.string "I am still upset about losing!$"

Route104_Text_WinstonIntro: @ 8295870
	.string "You haven't seen Fallen around here,\n"
	.string "have you?$"

Route104_Text_WinstonDefeat: @ 82958AD
	.string "He was trying to rope me into something…$"

Route104_Text_WinstonPostBattle: @ 82958C1
	.string "He was trying to rope me into something…$"

Route104_Text_WinstonRegister1: @ 82958F8
	.string "Hm?\n"
	.string "Ah, you've obtained a PokéNav.\p"
	.string "I will gladly register you.\n"
	.string "After all, I have plenty of money.$"

Route104_Text_WinstonRegister2: @ 829595A
	.string "Hm?\n"
	.string "Ah, you've obtained a PokéNav.\p"
	.string "I will gladly register you.\n"
	.string "After all, I have plenty of money.$"

Route104_Text_WinstonRematchIntro: @ 82959BC
	.string "After I lost to you, I learned a bunch\n"
	.string "of things about Pokémon.$"

Route104_Text_WinstonRematchDefeat: @ 82959FC
	.string "I lost again?\n"
	.string "Why couldn't I win?$"

Route104_Text_WinstonPostRematch: @ 8295A1E
	.string "I'm fabulously wealthy, but I can't\n"
	.string "seem to win at Pokémon…\p"
	.string "It's so deep, the world of Pokémon…$"

Route104_Text_CindyIntro: @ 8295A7E
	.string "NO! I won't look at your custom cards!\n"
	.string "I'm not wording any more war crimes!$"

Route104_Text_CindyDefeat: @ 8295ABB
	.string "Oh, you just wanted to battle?$"

Route104_Text_CindyPostBattle: @ 8295AC3
	.string "Whew, I'm glad you're not a designer.\n"
	.string "Anyway wanna hear about Lloyd MC?$"

Route104_Text_CindyRegister1: @ 8295B01
	.string "Hello, we meet again.\p"
	.string "We seem to be drawn together. Let's\n"
	.string "register each other in our PokéNavs.$"

Route104_Text_CindyRegister2: @ 8295B60
	.string "We should commemorate how we seem\n"
	.string "to be drawn to each other.\p"
	.string "Let's register each other in our\n"
	.string "PokéNavs.$"

Route104_Text_CindyRematchIntro: @ 8295BC8
	.string "Hello, we meet again.\n"
	.string "May I ask you for a battle?$"

Route104_Text_CindyRematchDefeat: @ 8295BFA
	.string "Oh, my…\n"
	.string "I did the best that I could…$"

Route104_Text_CindyPostRematch: @ 8295C1F
	.string "“Hello” is the beginning of “good-bye.”\n"
	.string "I hope we meet again.$"

Route104_Text_DarianIntro: @ 8295C5D
	.string "Hey, friend, how's it going?\n"
	.string "I haven't done much battling lately,\n"
	.string "but let's have a good match!$"

Route104_Text_DarianDefeat: @ 8295CC9
	.string "Well done!$"

Route104_Text_DarianPostBattle: @ 8295CD3
	.string "Well done!$"

Route105_Text_FosterIntro: @ 8295D0F
	.string "Okay, you don't have to join the Lissa\n"
	.string "fun club, but you should check out\l"
	.string "customs.$"

Route105_Text_FosterDefeated: @ 8295D62
	.string "…Yes, I did make a Lissa custom card…$"

Route105_Text_FosterPostBattle: @ 8295DAB
	.string "…Yes, I did make a Lissa custom card…$"

Route105_Text_LuisIntro: @ 8295DF5
	.string "How much do I like Blue? Well, I've\n"
	.string "got the blue starter decks, Chrom and\l"
	.string "Lucina deck boxes, a TON of blue cards…$"

Route105_Text_LuisDefeated: @ 8295E66
	.string "…And the summer Lucina playmat…$"

Route105_Text_LuisPostBattle: @ 8295E72
	.string "…And the summer Lucina playmat…$"

Route105_Text_DominikIntro: @ 8295EB7
	.string "48 65 6C 6C 6F 2C 20 57 65 6C 63 6F 6D\n"
	.string "65 20 74 6F 20 43 69 70 68 65 72 63 6F\p"
	.string "72 64 21 20$"

Route105_Text_DominikDefeated: @ 8295EEA
	.string "49 20 68 61 76 65 20 6C 6F 73 74$"

Route105_Text_DominikPostBattle: @ 8295F08
	.string "49 20 68 61 76 65 20 6C 6F 73 74$"

Route105_Text_BeverlyIntro: @ 8295F5C
	.string "Oh, you. I guess I can take a break\n"
	.string "from DnD prep to battle.$"

Route105_Text_BeverlyDefeated: @ 8295FA0
	.string "Hmm should I have the cabal of Corrin\n"
	.string "clones ambush them…?$"

Route105_Text_PostBattle: @ 8295FAE
	.string "Hmm should I have the cabal of Corrin\n"
	.string "clones ambush them…?$"

Route105_Text_ImaniIntro: @ 8296025
	.string "Some day I'll win a weekly…\n"
	.string "I just have to keep trying!$"

Route105_Text_ImaniDefeated: @ 8296059
	.string "I wonder how many times I'd have to\n"
	.string "fight you to win once…$"

Route105_Text_ImaniPostBattle: @ 8296076
	.string "I wonder how many times I'd have to\n"
	.string "fight you to win once…$"

Route105_Text_AndresIntro: @ 82960A9
	.string "You think this game is bullshit?\n"
	.string "I played when Racc was the 4th gym\l"
	.string "leader- his team was almost unchanged.$"

Route105_Text_AndresDefeated: @ 82960DB
	.string "Oh, also it was a jump scare double\n"
	.string "battle, which was SUPER fun.$"

Route105_Text_AndresPostBattle: @ 82960FA
	.string "Oh, also it was a jump scare double\n"
	.string "battle, which was SUPER fun.$"

Route105_Text_AndresRegister: @ 8296159
	.string "Huh? I'm so weak, but you're willing\n"
	.string "to register me in your PokéNav?$"

Route105_Text_AndresRematchIntro: @ 829619E
	.string "I've told you that I'm weak…\n"
	.string "Are you sure you want to do this?$"

Route105_Text_AndresRematchDefeated: @ 82961DD
	.string "Yes…\n"
	.string "I didn't think I could win.$"

Route105_Text_AndresRematchPostBattle: @ 82961FE
	.string "I may be weak at battling, but my\n"
	.string "drive to explore can't be bested.\p"
	.string "I will travel the seas all around\n"
	.string "the world!$"

Route105_Text_JosueIntro: @ 829626F
	.string "I'm exhausted from swimming.\n"
	.string "I'm just not used to it.\p"
	.string "I need a battle for a change of pace!$"

Route105_Text_JosueDefeated: @ 82962CB
	.string "I lost because I battled at sea.$"

Route105_Text_JosuePostBattle: @ 82962EC
	.string "Yeah, for me, the sky is a much better\n"
	.string "match than the sea.$"

Route106_Text_ElliotIntro: @ 8296327
	.string "Oh hey, I can fight you and not have\n"
	.string "to worry about timezones.$"

Route106_Text_ElliotDefeated: @ 829635C
	.string "Heh, hey never see the Zoroark coming.$"

Route106_Text_ElliotPostBattle: @ 829638C
	.string "Heh, hey never see the Zoroark coming.$"

Route106_Text_ElliotRegister: @ 82963E3
	.string "Fishing's great, but so is battling.\n"
	.string "If you don't mind, can we meet again?$"

Route106_Text_ElliotRematchIntro: @ 829642E
	.string "I caught a bunch of Pokémon fishing.\n"
	.string "I'll show you an impressive battle!$"

Route106_Text_ElliotRematchDefeated: @ 8296477
	.string "I lost again spectacularly!$"

Route106_Text_ElliotRematchPostBattle: @ 8296493
	.string "Win or lose, Pokémon are the greatest!\n"
	.string "You agree with me, right?$"

Route106_Text_NedIntro: @ 82964D4
	.string "Hmm… I suppose I can take a break from\n"
	.string "watching others to fight for my\l"
	.string "amusement to battle you.$"

Route106_Text_NedDefeated: @ 8296553
	.string "What? You got a problem with penguins?$"

Route106_Text_NedPostBattle: @ 8296588
	.string "What? You got a problem with penguins?$"

Route106_Text_DouglasIntro: @ 82965BB
	.string "I spent way too much time playing RD\n"
	.string "for it to turn out so mid…$"

Route106_Text_DouglasDefeated: @ 82965FD
	.string "I beat the game, but I kinda hated it.$"

Route106_Text_DouglasPostBattle: @ 8296608
	.string "I beat the game, but I kinda hated it.$"

Route106_Text_KylaIntro: @ 8296628
	.string "Cats are the best!$"

Route106_Text_KylaDefeated: @ 8296674
	.string "Blaziken is cool too! =)$"

Route106_Text_KylaPostBattle: @ 829669E
	.string "Blaziken is cool too! =)$"

Route107_Text_DarrinIntro: @ 82966E5
	.string "You again? You here to sign up for a\n"
	.string "tourney finally?\p"
	.string "…Fine, I'll drop the eeveelutions for\n"
	.string "just this match- so get ready to get\l"
	.string "your ass beat.$"

Route107_Text_DarrinDefeated: @ 829672F
	.string "Fucking donkey shit.\p"
	.string "I mean good game.$"

Route107_Text_DarrinPostBattle: @ 829675B
	.string "Fucking donkey shit.\p"
	.string "I mean good game.$"

Route107_Text_TonyIntro: @ 82967AD
	.string "Oh yo what's up? I'm taking a break\n"
	.string "from helping Fallen, but we can still\l"
	.string "battle.$"

Route107_Text_TonyDefeated: @ 82967D8
	.string "Damn, gettin sacked even on vacation!$"

Route107_Text_TonyPostBattle: @ 82967FF
	.string "Damn, gettin sacked even on vacation!$"

Route107_Text_TonyRegister: @ 829685A
	.string "You've shocked me to the bone!\n"
	.string "Well, so you won't forget me…$"

Route107_Text_TonyRematchIntro: @ 8296897
	.string "Swimming in the big, wide sea,\n"
	.string "my Pokémon has grown stronger!$"

Route107_Text_TonyRematchDefeated: @ 82968D5
	.string "What a shock!\p"
	.string "My Pokémon has gotten stronger, but\n"
	.string "I stayed weak as a Trainer!$"

Route107_Text_TonyRematchPostBattle: @ 8296923
	.string "What you learn in battle makes you\n"
	.string "a stronger Trainer.\l"
	.string "The waves taught me that.$"

Route107_Text_DeniseIntro: @ 8296974
	.string "I left the Gardevoir house becuase\n"
	.string "of you- Let me show you what I've\l"
	.string "learned since!$"

Route107_Text_DeniseDefeated: @ 829699E
	.string "Maybe I should have kep Gardevoir.$"

Route107_Text_DenisePostBattle: @ 82969AB
	.string "Maybe I should have kep Gardevoir.$"

Route107_Text_BethIntro: @ 82969E4
	.string "Huh? Who're you?\n"
	.string "Eh whatever, let's fuckin' FIGHT!$"

Route107_Text_BethDefeated: @ 8296A17
	.string "Damn, ggs.$"

Route107_Text_BethPostBattle: @ 8296A35
	.string "Damn, ggs.$"

Route107_Text_LisaIntro: @ 8296A77
	.string "Lisa: We challenge you as a sister\n"
	.string "and brother!$"

Route107_Text_LisaDefeated: @ 8296AA7
	.string "Lisa: Awesome.\n"
	.string "You're in a different class of tough.$"

Route107_Text_LisaPostBattle: @ 8296ADC
	.string "Lisa: Do you have any friends who\n"
	.string "would go to the beach with you?$"

Route107_Text_LisaNotEnoughPokemon: @ 8296B1E
	.string "Lisa: If you want to battle with us,\n"
	.string "bring more Pokémon.$"

Route107_Text_RayIntro: @ 8296B57
	.string "Ray: We always battle Pokémon,\n"
	.string "me and my sister.\p"
	.string "I always lose, but we can beat you\n"
	.string "2-on-2!$"

Route107_Text_RayDefeated: @ 8296BB3
	.string "Ray: Wowee, you're at a higher level\n"
	.string "than us!$"

Route107_Text_RayPostBattle: @ 8296BE1
	.string "Ray: My sister gave me my Pokémon.\n"
	.string "I raised it, and now it's my important\l"
	.string "partner!$"

Route107_Text_RayNotEnoughPokemon: @ 8296C34
	.string "Ray: If you want to battle us,\n"
	.string "go bring some more Pokémon!$"

Route107_Text_CamronIntro: @ 8296C6F
	.string "I'm in the middle of a triathlon,\n"
	.string "but I'm nowhere near tired!$"

Route107_Text_CamronDefeated: @ 8296CAD
	.string "That exhausted me…$"

Route107_Text_CamronPostBattle: @ 8296CC0
	.string "I still have swimming and running left\n"
	.string "to do after this.\p"
	.string "Am I going to be okay?$"

Route108_Text_JeromeIntro: @ 8296D10
	.string "I'm still a beginner, pls go easy on\n"
	.string "me! :3$"

Route108_Text_JeromeDefeated: @ 8296D3C
	.string "Aww man…$"

Route108_Text_JeromePostBattle: @ 8296D6E
	.string "Aww man…$"

Route108_Text_MatthewIntro: @ 8296DAF
	.string "Ahoy, there! Are you going out to\n"
	.string "the Abandoned Ship, too?$"

Route108_Text_MatthewDefeated: @ 8296DEA
	.string "I'm sinking!\n"
	.string "Glub… Glub…$"

Route108_Text_MatthewPostBattle: @ 8296E03
	.string "Some people even go inside that\n"
	.string "Abandoned Ship.$"

Route108_Text_TaraIntro: @ 8296E33
	.string "Apparently there were already too\n"
	.string "many Gardevoirs and Gallades in\l"
	.string "this hack…$"

Route108_Text_TaraDefeated: @ 8296E71
	.string "At least most of my team is here.$"

Route108_Text_TaraPostBattle: @ 8296E7A
	.string "At least most of my team is here.$"

Route108_Text_MissyIntro: @ 8296EC7
	.string "I've played Grima off and on for two\n"
	.string "years and have yet to win one game…$"

Route108_Text_MissyDefeated: @ 8296EFC
	.string "I just gave up and started playing\n"
	.string "Sigurd- and actually won something.$"

Route108_Text_MissyPostBattle: @ 8296F2A
	.string "I just gave up and started playing\n"
	.string "Sigurd- and actually won something.$"

Route108_Text_CoryIntro: @ 8296F5D
	.string "I love Water-type Pokémon.\n"
	.string "I love other Pokémon, too!$"

Route108_Text_CoryDefeated: @ 8296F93
	.string "Waaah! I lost!\n"
	.string "Waaah! Waaah!$"

Route108_Text_CoryPostBattle: @ 8296FB0
	.string "Shouting is good for me!\n"
	.string "It uplifts me!$"

Route108_Text_CoryRegister: @ 8296FD8
	.string "I love tough Trainers, too!\n"
	.string "Register me in your PokéNav!$"

Route108_Text_CoryRematchIntro: @ 8297011
	.string "Win or lose, I love battling at sea!$"

Route108_Text_CoryRematchDefeated: @ 8297036
	.string "Waaah! I lost again!\n"
	.string "Waaah! Waaah!$"

Route108_Text_CoryRematchPostBattle: @ 8297059
	.string "If you're faced with a challenge,\n"
	.string "try shouting at the sea!$"

Route108_Text_CarolinaIntro: @ 8297094
	.string "I take huge pride in my Pokémon.\n"
	.string "We'll show you one speedy battle!$"

Route108_Text_CarolinaDefeated: @ 82970D7
	.string "That wasn't cute at all.$"

Route108_Text_CarolinaPostBattle: @ 82970F0
	.string "Since I'm at sea like this, I wouldn't\n"
	.string "mind putting on a pink, frilly swimsuit…$"

Route109_Text_DavidIntro: @ 8297140
	.string "Got second in AMAs from bad matchups,\n"
	.string "now I'm probably too good to join the\l"
	.string "next one…$"

Route109_Text_DavidDefeated: @ 829717D
	.string "I'm not angry, more sad…$"

Route109_Text_DavidPostBattle: @ 8297191
	.string "I'm not angry, more sad…$"

Route109_Text_AliceIntro: @ 82971D1
	.string "You know what they say, it's sink or\n"
	.string "swim!$"

Route109_Text_AliceDefeated: @ 82971FD
	.string "Guess i'm the one sinking…$"

Route109_Text_AlicePostBattle: @ 829720F
	.string "Guess i'm the one sinking…$"

Route109_Text_HueyIntro: @ 8297235
	.string "Alright, let's get this over with.$"

Route109_Text_HueyDefeated: @ 829727B
	.string "…Bad game.$"

Route109_Text_HueyPostBattle: @ 829728C
	.string "Good to know this game has bullshit\n"
	.string "luck in it too.$"

Route109_Text_EdmondIntro: @ 82972B3
	.string "01101001 00100000 01100110 01101001\n"
	.string "01100111 01101000 01110100 00100000\l"
	.string "01101110 01101111 01110111$"

Route109_Text_EdmondDefeated: @ 82972CE
	.string "01100100 01100001 01101101 01101110$"

Route109_Text_EdmondPostBattle: @ 82972ED
	.string "01100100 01100001 01101101 01101110$"

Route109_Text_RickyIntro: @ 829733B
	.string "This is an Ivy fan account.\n"
	.string "How can I help you?$"

Route109_Text_RickyDefeated: @ 8297379
	.string "Someday I'll get her to +10…$"

Route109_Text_RickyPostBattle: @ 8297380
	.string "Someday I'll get her to +10…$"

Route109_Text_RickyRegister: @ 82973C1
	.string "Will you have another match with me\n"
	.string "when I'm not all thirsty?$"

Route109_Text_RickyRematchIntro: @ 82973FF
	.string "I'm hungry, but I've got enough pep in\n"
	.string "me for a battle!$"

Route109_Text_RickyRematchDefeated: @ 8297437
	.string "I lost…\n"
	.string "It's because I'm hungry…$"

Route109_Text_RickyRematchPostBattle: @ 8297458
	.string "When you eat on a beach, everything\n"
	.string "seems to taste a little better.$"

Route109_Text_LolaIntro: @ 829749C
	.string "Doesn't a beach umbrella look like\n"
	.string "a giant flower?$"

Route109_Text_LolaDefeated: @ 82974CF
	.string "Mommy!$"

Route109_Text_LolaPostBattle: @ 82974D6
	.string "If you look at the beach from the sky,\n"
	.string "it looks like a big flower garden!$"

Route109_Text_LolaRegister: @ 8297520
	.string "Me?\n"
	.string "I'm here every day!$"

Route109_Text_LolaRematchIntro: @ 8297538
	.string "I'm not losing to you again!\n"
	.string "That's why I have my inner tube!$"

Route109_Text_LolaRematchDefeated: @ 8297576
	.string "Mommy!$"

Route109_Text_LolaRematchPostBattle: @ 829757D
	.string "If I have an inner tube, me and my\n"
	.string "Pokémon's cuteness goes way up!$"

Route109_Text_AustinaIntro: @ 82975C0
	.string "The next Fanseries set? It's coming\n"
	.string "along, but we're taking our time.\p"
	.string "We got some incredible new artists\n"
	.string "for this one, can't wait to show you.$"

Route109_Text_AustinaDefeated: @ 8297601
	.string "Of course, if you REALLY want to see\n"
	.string "them now, you can join our discord.$"

Route109_Text_AustinaPostBattle: @ 829762A
	.string "Of course, if you REALLY want to see\n"
	.string "them now, you can join our discord.$"

Route109_Text_GwenIntro: @ 8297667
	.string "Hi, big Trainer.\n"
	.string "Will you battle with me?$"

Route109_Text_GwenDefeated: @ 8297691
	.string "Oh, you're strong.$"

Route109_Text_GwenPostBattle: @ 82976A4
	.string "How did you get to be so strong?$"

Route109_Text_CarterIntro: @ 82976C5
	.string "Wahahah! This dude's going to catch\n"
	.string "himself a big one!$"

Route109_Text_CarterDefeated: @ 82976FC
	.string "This dude just lost one…$"

Route109_Text_CarterPostBattle: @ 8297715
	.string "This dude thinks you're a big one.\n"
	.string "No, you're a big-one-to-be!$"

Route109_Text_PaulIntro: @ 8297754
	.string "Paul: Well, this is a mood-breaker.\p"
	.string "I wish you wouldn't disturb our\n"
	.string "precious time together.$"

Route109_Text_PaulDefeated: @ 82977B0
	.string "Paul: Well, I give up.$"

Route109_Text_PaulPostBattle: @ 82977C7
	.string "Paul: Well, don't tell anyone that\n"
	.string "we're here.\l"
	.string "This is just our private world of two!$"

Route109_Text_PaulNotEnoughPokemon: @ 829781D
	.string "Paul: We're totally, deeply in love.\n"
	.string "That's why we make our Pokémon battle\l"
	.string "together.$"

Route109_Text_MelIntro: @ 8297872
	.string "Mel: We're, like, totally in love.\n"
	.string "Our romance is heating up all of Hoenn!$"

Route109_Text_MelDefeated: @ 82978BD
	.string "Mel: We lost, and it's my fault!\n"
	.string "Paul will hate me!$"

Route109_Text_MelPostBattle: @ 82978F1
	.string "Mel: Um, Paul, are you angry with me?\n"
	.string "Please don't be angry.$"

Route109_Text_MelNotEnoughPokemon: @ 829792E
	.string "Mel: We're, like, deeply and truly in love.\n"
	.string "That's why we make our Pokémon\l"
	.string "battle together.$"

Route109_Text_ChandlerIntro: @ 829798A
	.string "Tadaah! See?\n"
	.string "My inner tube's round!$"

Route109_Text_ChandlerDefeated: @ 82979AE
	.string "Oh, oh!\n"
	.string "Too bad!$"

Route109_Text_ChandlerPostBattle: @ 82979BF
	.string "After I showed you my round inner\n"
	.string "tube, too…$"

Route109_Text_HaileyIntro: @ 82979EC
	.string "Hmm… Which blue aggro deck should I play?\n"
	.string "Battle with me until I can decide!$"

Route109_Text_HaileyDefeated: @ 8297A15
	.string "Alright, I'll go with Frederick!$"

Route109_Text_HaileyPostBattle: @ 8297A40
	.string "Alright, I'll go with Frederick!$"

Route109_Text_ElijahIntro: @ 8297A82
	.string "I miss Dragalia Lost, much better\n"
	.string "game than FeH imo.$"

Route109_Text_ElijahDefeated: @ 8297AC7
	.string "Then we lost Dr. Mario and Pocket\n"
	.string "camp- when is it FeH's turn?$"

Route109_Text_ElijahPostBattle: @ 8297AE5
	.string "Then we lost Dr. Mario and Pocket\n"
	.string "camp- when is it FeH's turn?$"

Route110_Text_JacobIntro: @ 8297B3F
	.string "Whoa! Watch it!\n"
	.string "I guess you're not used to Bike racing.$"

Route110_Text_JacobDefeated: @ 8297B77
	.string "Whoa!\n"
	.string "My brakes failed!$"

Route110_Text_JacobPostBattle: @ 8297B8F
	.string "Flat tires and brake problems can\n"
	.string "cause serious injury!\l"
	.string "Inspect your Bike for problems!$"

Route110_Text_AnthonyIntro: @ 8297BE7
	.string "I may have given up on getting a\n"
	.string "playset of everything, but I still\l"
	.string "want to shoot for 1 of each.$"

Route110_Text_AnthonyDefeated: @ 8297C0F
	.string "Might take a while, but I'll get it.$"

Route110_Text_AnthonyPostBattle: @ 8297C1F
	.string "Might take a while, but I'll get it.$"

Route110_Text_BenjaminIntro: @ 8297C63
	.string "Pokémon, like FEH, is best when all\n"
	.string "you have to do is click buttons.$"

Route110_Text_BenjaminDefeated: @ 8297C8A
	.string "I do like clickin buttons yessir.$"

Route110_Text_BenjaminPostBattle: @ 8297CB4
	.string "I do like clickin buttons yessir.$"

Route110_Text_BenjaminRegister: @ 8297CFE
	.string "I'll keep chugging on without stressing.\n"
	.string "Give me a shout if you're up to it.$"

Route110_Text_BenjaminRematchIntro: @ 8297D4B
	.string "Aren't you going a little too fast?\n"
	.string "Take it easy and let's battle.$"

Route110_Text_BenjaminRematchDefeated: @ 8297D8E
	.string "I didn't panic, but I still lost…$"

Route110_Text_BenjaminRematchPostBattle: @ 8297DB0
	.string "There's no need to panic or stress.\n"
	.string "Take it easy. There's plenty of time.$"

Route110_Text_AbigailIntro: @ 8297DFA
	.string "Kinda in the middle of something\n"
	.string "here, can we be quick?$"

Route110_Text_AbigailDefeated: @ 8297E69
	.string "Now if you'll excuse me, I have\n"
	.string "XC1 to play.$"

Route110_Text_AbigailPostBattle: @ 8297E88
	.string "Now if you'll excuse me, I have\n"
	.string "XC1 to play.$"

Route110_Text_AbigailRegister: @ 8297ECD
	.string "You know, I like you!\n"
	.string "Let's have a rematch on Cycling Road.$"

Route110_Text_AbigailRematchIntro: @ 8297F09
	.string "Isn't it neat to hold a battle while\n"
	.string "cycling?$"

Route110_Text_AbigailRematchDefeated: @ 8297F37
	.string "Wow…\n"
	.string "How could you be so strong?$"

Route110_Text_AbigailRematchPostBattle: @ 8297F58
	.string "Were you going after a record?\p"
	.string "I'm sorry if I held you up!$"

Route110_Text_JasmineIntro: @ 8297F93
	.string "I'm probably one of the only people\n"
	.string "to ever cosplay as a Cipher OC.$"

Route110_Text_JasmineDefeated: @ 8297FD0
	.string "One of the others is my wife!$"

Route110_Text_JasminePostBattle: @ 8297FF1
	.string "One of the others is my wife!$"

Route110_Text_EdwardIntro: @ 829802B
	.string "I have foreseen your intentions!\n"
	.string "I cannot possibly lose!$"

Route110_Text_EdwardDefeated: @ 8298064
	.string "I failed to prophesize my own demise!$"

Route110_Text_EdwardPostBattle: @ 829808A
	.string "I see your future…\p"
	.string "Hmm…\n"
	.string "I see a shining light…$"

Route110_Text_JaclynIntro: @ 82980B9
	.string "Hi, mind if I test out a new\n"
	.string "team on you?$"

Route110_Text_JaclynDefeated: @ 82980E5
	.string "Hmm, seems like it needs some work.$"

Route110_Text_JaclynPostBattle: @ 82980F8
	.string "Thanks for testing with me. My usual\n"
	.string "team got me pretty far, but I was\l"
	.string "looking to try something new.\p"
	.string "I have a feeling I'll see you later.$"

Route110_Text_EdwinIntro: @ 829815E
	.string "I LOVE Tarountula!$"

Route110_Text_EdwinDefeated: @ 829818F
	.string "I wish this game actually had gen 9…$"

Route110_Text_EdwinPostBattle: @ 82981B3
	.string "I wish this game actually had gen 9…$"

Route110_Text_EdwinRegister: @ 8298201
	.string "I like collecting Match Call\n"
	.string "registrations, too…$"

Route110_Text_EdwinRematchIntro: @ 8298232
	.string "Hi, have you caught any new Pokémon?\p"
	.string "Could I see your Pokémon?\n"
	.string "Just one look, please?$"

Route110_Text_EdwinRematchDefeated: @ 8298288
	.string "Your Pokémon…\n"
	.string "I envy you.$"

Route110_Text_EdwinRematchPostBattle: @ 82982A2
	.string "Oh, I long to make all rare Pokémon\n"
	.string "mine!$"

Route110_Text_DaleIntro: @ 82982CC
	.string "Hey! Do you collect Cipher cards?\n"
	.string "Or want to share your decks?\p"
	.string "You should visit Cipher Compendium!$"

Route110_Text_DaleDefeated: @ 82982F5
	.string "I may have lost, but you should\n"
	.string "still check it out!$"

Route110_Text_DalePostBattle: @ 8298303
	.string "I may have lost, but you should\n"
	.string "still check it out!$"

Route110_Text_IsabelIntro: @ 8298349
	.string "Hmm… Which of my Mercedes builds do\n"
	.string "I play here…?$"

Route110_Text_IsabelDefeated: @ 8298389
	.string "Damn, can't believe I got counter\n"
	.string "picked.$"

Route110_Text_IsabelPostBattle: @ 82983A2
	.string "Damn, can't believe I got counter\n"
	.string "picked.$"

Route110_Text_IsabelRegister: @ 82983EE
	.string "That wasn't close to what I could\n"
	.string "do to show off my Pokémon.\p"
	.string "I'll have you as my captive audience\n"
	.string "as often as possible!$"

Route110_Text_IsabelRematchIntro: @ 8298466
	.string "Ahahahaha! I would be happy to show\n"
	.string "off my Pokémon as often as you like!$"

Route110_Text_IsabelRematchDefeated: @ 82984AF
	.string "Oh, dear, this won't do.$"

Route110_Text_IsabelRematchPostBattle: @ 82984C8
	.string "I don't think that I could ever stop\n"
	.string "from showing off my Pokémon.\p"
	.string "But I like to battle, too!$"

Route110_Text_TimmyIntro: @ 8298525
	.string "Ah, do you need me to update the\n"
	.string "sheet?\p"
	.string "…Oh, a battle? I suppose.$"

Route110_Text_TimmyDefeated: @ 8298559
	.string "Hopefully that bot works soon…$"

Route110_Text_TimmyPostBattle: @ 8298579
	.string "Hopefully that bot works soon…$"

Route110_Text_AlyssaIntro: @ 82985AB
	.string "I fell off Cycling Road…\p"
	.string "I'll get over my embarrassment by\n"
	.string "battling with you!$"

Route110_Text_AlyssaDefeated: @ 82985F9
	.string "Oops!\n"
	.string "I ended up losing!$"

Route110_Text_AlyssaPostBattle: @ 8298612
	.string "Falling… Losing…\n"
	.string "This is so humiliating for me!$"

Route110_Text_JosephIntro: @ 8298642
	.string "Idk why I was put so early in this\n"
	.string "game. I play way more mons than\p"
	.string "these frauds.$"

Route110_Text_JosephDefeated: @ 8298686
	.string "NERD ALERT NERD ALERT NERD ALERT$"

Route110_Text_JosephPostBattle: @ 82986A9
	.string "NERD ALERT NERD ALERT NERD ALERT$"

Route110_Text_KalebIntro: @ 82986ED
	.string "LackeyDuelist gaming?$"

Route110_Text_KalebDefeated: @ 8298735
	.string "That was a rad battle- thanks for\n"
	.string "the match.$"

Route110_Text_KalebPostBattle: @ 8298755
	.string "That was a rad battle- thanks for\n"
	.string "the match.$"

Route111_Text_DrewIntro: @ 829878E
	.string "Oh its you again. You know, I've\n"
	.string "been thinking of trying a new deck.\p"
	.string "How do you feel about deckout Sophia?$"

Route111_Text_DrewDefeat: @ 829880A
	.string "Look if my opponent is having fun,\n"
	.string "then I'm not.$"

Route111_Text_DrewPostBattle: @ 8298853
	.string "Look if my opponent is having fun,\n"
	.string "then I'm not.$"

Route111_Text_HeidiIntro: @ 82988A3
	.string "For some reason, people don't seem\n"
	.string "to really like playing against me.\p"
	.string "Might have to do with Henry being\n"
	.string "my favorite deck.$"

Route111_Text_HeidiDefeat: @ 8298908
	.string "I'll stop playing Henry when it stops\n"
	.string "being the most fun deck to play.$"

Route111_Text_HeidiPostBattle: @ 829891B
	.string "I'll stop playing Henry when it stops\n"
	.string "being the most fun deck to play.$"

Route111_Text_BeauIntro: @ 829898E
	.string "My son just asked me what my favorite\n"
	.string "Pokémon are. I know a few since I play\l"
	.string "Pokémon GO, but that's about it…$"

Route111_Text_BeauDefeat: @ 82989E6
	.string "This is much harder than raids…$"

Route111_Text_BeauPostBattle: @ 8298A03
	.string "This is much harder than raids…$"

Route111_Text_BeckyIntro: @ 8298A65
	.string "Still holding out hope that they'll\n"
	.string "add more of the Laguz to FeH soon…$"

Route111_Text_BeckyDefeat: @ 8298AAF
	.string "Yeah, I know its copium…$"

Route111_Text_BeckyPostBattle: @ 8298AC0
	.string "Yeah, I know its copium…$"

Route111_Text_DustyIntro: @ 8298B08
	.string "Look, stop asking me about AD01.\n"
	.string "The review team took that over\l"
	.string "ages ago, go complain to them.$"

Route111_Text_DustyDefeat: @ 8298B53
	.string "My Engage set is cooking though, you\n"
	.string "wanna see?$"

Route111_Text_DustyPostBattle: @ 8298B9A
	.string "My Engage set is cooking though, you\n"
	.string "wanna see?$"

Route111_Text_DustyRegister: @ 8298C00
	.string "I haven't been searching for any\n"
	.string "tough Pokémon.\p"
	.string "But, for some reason, I sure do like\n"
	.string "PokéNavs.$"

Route111_Text_DustyRematchIntro: @ 8298C5F
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years?\n"
	.string "Anyway, am I to be challenged?$"

Route111_Text_DustyRematchDefeat: @ 8298CD2
	.string "I've found no ruins, nor have I found\n"
	.string "any strong Pokémon…$"

Route111_Text_DustyPostRematch: @ 8298D0C
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years\n"
	.string "I've searched?\p"
	.string "Hmm… It could even be fifty…\n"
	.string "How long have I been at this?$"

Route111_Text_TravisIntro: @ 8298DA9
	.string "Plz dm me about comiket boxes.$"

Route111_Text_TravisDefeat: @ 8298DD8
	.string "Yeah, still looking…$"

Route111_Text_TravisPostBattle: @ 8298DF1
	.string "Yeah, still looking…$"

Route111_Text_IreneIntro: @ 8298E2F
	.string "Oh hey, I was just coming up with a\n"
	.string "cool new shitty Nino deck.$"

Route111_Text_IreneDefeat: @ 8298E6E
	.string "I'll probably just play Roy next time…$"

Route111_Text_IrenePostBattle: @ 8298E8C
	.string "I'll probably just play Roy next time…$"

Route111_Text_DaisukeIntro: @ 8298EE6
	.string "Man, its been a while since I've\n"
	.string "popped in here.\p"
	.string "Wonder if Aku, Koku, Tibs and everyone\n"
	.string "are still around.$"

Route111_Text_DaisukeDefeat: @ 8298F14
	.string "Let me know if you see any of them!$"

Route111_Text_DaisukePostBattle: @ 8298F26
	.string "Let me know if you see any of them!$"

Route111_Text_WiltonIntro: @ 8298F79
	.string "Hey, want to check out my Rinkah\n"
	.string "deck?$"

Route111_Text_WiltonDefeat: @ 8298FA9
	.string "I see, you've toughened them\n"
	.string "considerably.$"

Route111_Text_WiltonPostBattle: @ 8298FD4
	.string "Should probably cut Benny huh…$"

Route111_Text_WiltonRegister: @ 829903D
	.string "There is much to be learned from\n"
	.string "your training style.\p"
	.string "I request a rematch if it\n"
	.string "behooves you.$"

Route111_Text_WiltonRematchIntro: @ 829909B
	.string "We're training here to elevate our\n"
	.string "game to the next level.\l"
	.string "Stay and train with us!$"

Route111_Text_WiltonRematchDefeat: @ 82990EE
	.string "Ooh, you're decent!$"

Route111_Text_WiltonPostRematch: @ 8299102
	.string "Since you're that strong, you should\n"
	.string "aim for the Pokémon League.$"

Route111_Text_BrookeIntro: @ 8299143
	.string "A battle? Sure, what game? I do\n"
	.string "Vanguard, Shadowverse, Yugioh,\l"
	.string "hell I might even play Cipher.$"

Route111_Text_BrookeDefeat: @ 8299193
	.string "Oh, Pokémon?$"

Route111_Text_BrookePostBattle: @ 82991C2
	.string "Oh, Pokémon?$"

Route111_Text_BrookeRegister: @ 829921D
	.string "I wish I could become friends with\n"
	.string "more strong people like you!$"

Route111_Text_BrookeRematchIntro: @ 829925D
	.string "You can make Pokémon stronger or\n"
	.string "weaker depending on the moves you\l"
	.string "teach them.\p"
	.string "What kinds of moves do your Pokémon\n"
	.string "know?$"

Route111_Text_BrookeRematchDefeat: @ 82992D6
	.string "You've taught them good moves!$"

Route111_Text_BrookePostRematch: @ 82992F5
	.string "Maybe I should have stopped my\n"
	.string "Pokémon from evolving until they\l"
	.string "learned better moves…$"

Route111_Text_CeliaIntro: @ 829934B
	.string "Huh? You again? Here to rob me with\n"
	.string "bullshit luck again?$"

Route111_Text_CeliaDefeat: @ 8299384
	.string "Bad game.$"

Route111_Text_CeliaPostBattle: @ 82993A7
	.string "This game has worse balance than\n"
	.string "Cipher. And that game has fucking\l"
	.string "Valla in it.$"

Route111_Text_BryanIntro: @ 8299401
	.string "Mmm, I guess I can take a break\n"
	.string "from LoR to do a match.$"

Route111_Text_BryanDefeat: @ 8299431
	.string "Losing to you is better than\n"
	.string "another Elder Dragon deck…$"

Route111_Text_BryanPostBattle: @ 829945F
	.string "Losing to you is better than\n"
	.string "another Elder Dragon deck…$"

Route111_Text_BrandenIntro: @ 8299493
	.string "Man, being retired is so nice. I\n"
	.string "get to pop in, see whatever chaos\l"
	.string "is going on, and laugh.$"

Route111_Text_BrandenDefeat: @ 82994C5
	.string "Like HoYOC2? Peak spectator\n"
	.string "experience. Would never join.$"

Route111_Text_BrandenPostBattle: @ 82994FB
	.string "Like HoYOC2? Peak spectator\n"
	.string "experience. Would never join.$"

Route111_Text_TyronIntro: @ 8299524
	.string "Look, I like Lucina a NORMAL amount.$"

Route111_Text_TyronDefeat: @ 8299549
	.string "I swear all of Aegis's emotes are out\n"
	.string "of context. Just don't look at them.$"

Route111_Text_TyronPostBattle: @ 8299576
	.string "I swear all of Aegis's emotes are out\n"
	.string "of context. Just don't look at them.$"

Route111_Text_CelinaIntro: @ 82995F0
	.string "Hey there, wanna VC for our match?\p"
	.string "…Wait, we're already talking?$"

Route111_Text_CelinaDefeat: @ 8299625
	.string "Pain.$"

Route111_Text_CelinaPostBattle: @ 829964B
	.string "Pain.$"

Route111_Text_HaydenIntro: @ 8299682
	.string "When you're as famished as I am,\n"
	.string "there is no room for pity!$"

Route111_Text_HaydenDefeat: @ 82996BE
	.string "Groan…$"

Route111_Text_HaydenPostBattle: @ 82996C5
	.string "My stomach is grumbling!\n"
	.string "Maybe I can grill some BERRIES…$"

Route111_Text_BiancaIntro: @ 82996FE
	.string "I'm bad at Pokémon, but I'll give\n"
	.string "it my best shot!$"

Route111_Text_BiancaDefeat: @ 829973D
	.string "Yeah, my team needs some work.$"

Route111_Text_BiancaPostBattle: @ 829975D
	.string "Yeah, my team needs some work.$"

Route112_Text_BriceIntro: @ 829978E
	.string "I wish Fem Kris got a summer alt.$"

Route112_Text_BriceDefeat: @ 82997CA
	.string "Like even SHEZ got one before her.$"

Route112_Text_BricePostBattle: @ 82997DC
	.string "Like even SHEZ got one before her.$"

Route112_Text_TrentIntro: @ 8299815
	.string "Man, I've got all these Cipher boxes\n"
	.string "lying around.$"

Route112_Text_TrentDefeat: @ 829987C
	.string "Maybe I could give them away or something?$"

Route112_Text_TrentPostBattle: @ 8299896
	.string "Maybe I could give them away or something?$"

Route112_Text_TrentRegister: @ 829993C
	.string "Ow, my legs have cramped up.\n"
	.string "Can you grab me some bandages from\l"
	.string "my backpack?\p"
	.string "No, that's my PokéNav!\n"
	.string "Oh, fine, I'll register you.$"

Route112_Text_TrentRematchIntro: @ 82999BD
	.string "I've been keeping fit by hiking.\n"
	.string "Power, I have in spades!$"

Route112_Text_TrentRematchDefeat: @ 82999F7
	.string "I got trumped in power?$"

Route112_Text_TrentRematchPostBattle: @ 8299A0F
	.string "I hear there are some seriously tough\n"
	.string "Trainers on top of Mt. Chimney.\p"
	.string "I intend to get up there and give them\n"
	.string "a challenge!$"

Route112_Text_LarryIntro: @ 8299A89
	.string "Noble Phantasm: Ten Thousand Hammers!\n"
	.string "Kill this guy!$"

Route112_Text_LarryDefeat: @ 8299AAC
	.string "Mods, melt this guy's ice cream.$"

Route112_Text_LarryPostBattle: @ 8299AB4
	.string "Mods, melt this guy's ice cream.$"

Route112_Text_CarolIntro: @ 8299AE4
	.string "If you're a yellow player, don't blame\n"
	.string "me if I fall asleep mid-match.$"

Route112_Text_CarolDefeat: @ 8299B36
	.string "I just wish Seliph was midrange…$"

Route112_Text_CarolPostBattle: @ 8299B4C
	.string "I just wish Seliph was midrange…$"

Route112_Text_BryantIntro: @ 8299BAE
	.string "I caught hot Pokémon in Fiery Path!\n"
	.string "Take a look!$"

Route112_Text_BryantDefeat: @ 8299BDF
	.string "What a bumpy ride that was!$"

Route112_Text_BryantPostBattle: @ 8299BFB
	.string "I like the way you battle.\n"
	.string "It has a certain flair to it.$"

Route112_Text_ShaylaIntro: @ 8299C34
	.string "Oh hi, I don't really play much.\n"
	.string "Usually I just clean up full art and\l"
	.string "post it on twitter.$"

Route112_Text_ShaylaDefeat: @ 8299C8F
	.string "Back to scanning art books I go.$"

Route112_Text_ShaylaPostBattle: @ 8299CC6
	.string "Back to scanning art books I go.$"

Route113_Text_JaylenIntro: @ 8299D3C
	.string "If I win, we should do a webcam\n"
	.string "duel! Come on!$"

Route113_Text_JaylenDefeat: @ 8299D68
	.string "I suppose I'll have to see if Gats\n"
	.string "is free…$"

Route113_Text_JaylenPostBattle: @ 8299D7D
	.string "I suppose I'll have to see if Gats\n"
	.string "is free…$"

Route113_Text_DillonIntro: @ 8299DE3
	.string "Ddi the bot break? … … …\n"
	.string "Oh, it syou.$"

Route113_Text_DillonDefeat: @ 8299E1C
	.string "What? My keybord works fine.$"

Route113_Text_DillonPostBattle: @ 8299E38
	.string "What? My keybord works fine.$"

Route113_Text_MadelineIntro: @ 8299EA6
	.string "Morning! Are you here for my daily\n"
	.string "daily fox post?$"

Route113_Text_MadelineDefeat: @ 8299EF9
	.string "Oh well, see you for tomorrow's\n"
	.string "fox!$"

Route113_Text_MadelinePostBattle: @ 8299F15
	.string "Oh well, see you for tomorrow's\n"
	.string "fox!$"

Route113_Text_MadelineRegister: @ 8299F49
	.string "Here, slide under my parasol.\n"
	.string "Let me register you in my PokéNav.$"

Route113_Text_MadelineRematchIntro: @ 8299F8A
	.string "Oh, hello, hasn't it been a while?\n"
	.string "May I invite you to battle?$"

Route113_Text_MadelineRematchDefeat: @ 8299FC9
	.string "Oh, how super!$"

Route113_Text_MadelinePostRematch: @ 8299FD8
	.string "You've remained very good at this.\n"
	.string "I must say I'm impressed!$"

Route113_Text_LaoIntro: @ 829A015
	.string "Hey, put this in a youtube link:\p"
	.string "lN4 UNDERSCORE YlwNK1w$"

Route113_Text_LaoDefeat: @ 829A04C
	.string "Did I get you?$"

Route113_Text_LaoPostBattle: @ 829A067
	.string "Did I get you?$"

Route113_Text_LaoRegister: @ 829A0A2
	.string "Yiiyaah! Witness the ancient ninja\n"
	.string "technique of PokéNav registration!$"

Route113_Text_LaoRematchIntro: @ 829A0E8
	.string "From out of the ashes I leap! Hiyah!\n"
	.string "I challenge thee!$"

Route113_Text_LaoRematchDefeat: @ 829A11F
	.string "With honor I admit defeat!$"

Route113_Text_LaoPostRematch: @ 829A13A
	.string "My flawless concealment was let down\n"
	.string "by my immature battle skills…\p"
	.string "I bid thee farewell.$"

Route113_Text_LungIntro: @ 829A192
	.string "I mostly play the TCG nowadays, but\n"
	.string "I'll still do a real Pokémon battle!$"

Route113_Text_LungDefeat: @ 829A1C6
	.string "Maybe I'll stick to cards…$"

Route113_Text_LungPostBattle: @ 829A219
	.string "Maybe I'll stick to cards…$"

Route113_Text_ToriIntro: @ 829A261
	.string "Tori: Both of us, we collect ashes.\n"
	.string "We battle Pokémon, too.$"

Route113_Text_ToriDefeat: @ 829A29D
	.string "Tori: We lost… It's boring, so I'm going\n"
	.string "to get some more ashes.$"

Route113_Text_ToriPostBattle: @ 829A2DE
	.string "Tori: How much ash do we have?\n"
	.string "Enough for a White Flute, I hope.$"

Route113_Text_ToriNotEnoughMons: @ 829A31F
	.string "Tori: We want to battle 2-on-2.\n"
	.string "If we didn't, we would lose!$"

Route113_Text_TiaIntro: @ 829A35C
	.string "Tia: Both of us, we collect ashes.\n"
	.string "We battle Pokémon, too.$"

Route113_Text_TiaDefeat: @ 829A397
	.string "Tia: We couldn't win… It's boring,\n"
	.string "so I'm getting some more ashes.$"

Route113_Text_TiaPostBattle: @ 829A3DA
	.string "Tia: We have a lot of ashes!\n"
	.string "I think enough for a White Flute!$"

Route113_Text_TiaNotEnoughMons: @ 829A419
	.string "Tia: We want to battle 2-on-2.\n"
	.string "If we don't, we won't win!$"

Route113_Text_CobyIntro: @ 829A453
	.string "Hmm I haven't touched Cipher in a\n"
	.string "while, maybe I can join amas.$"

Route113_Text_CobyDefeat: @ 829A480
	.string "Eh, or I can just play Vanguard.$"

Route113_Text_CobyPostBattle: @ 829A489
	.string "Eh, or I can just play Vanguard.$"

Route113_Text_SophieIntro: @ 829A4BF
	.string "A Pokémon battle? Well I'm in the top\n"
	.string "100 Leos in Strive, how hard can it be?$"

Route113_Text_SophieDefeat: @ 829A508
	.string "Damn you beat my ass.$"

Route113_Text_SophiePostBattle: @ 829A529
	.string "Damn you beat my ass.$"

Route113_Text_LawrenceIntro: @ 829A566
	.string "Webcam duelist?? Anyone??\n"
	.string "Just fight me in something!$"

Route113_Text_LawrenceDefeat: @ 829A5A0
	.string "Man… Everyone hates me I guess…$"

Route113_Text_LawrencePostBattle: @ 829A5BE
	.string "Man… Everyone hates me I guess…$"

Route113_Text_WyattIntro: @ 829A5E4
	.string "Oh hey! I just got back from Tokyo-\n"
	.string "I got a bunch of Cipher singles there.$"

Route113_Text_WyattDefeat: @ 829A628
	.string "Hopefully I can still find a box\n"
	.string "or two somewhere.$"

Route113_Text_WyattPostBattle: @ 829A65D
	.string "Hopefully I can still find a box\n"
	.string "or two somewhere.$"

Route114_Text_LennyIntro: @ 829A6B1
	.string "YO! A Pokémon battle?\p"
	.string "BETTER CALL HEXA!$"

Route114_Text_LennyDefeat: @ 829A707
	.string "I shouldn't have picked up…$"

Route114_Text_LennyPostBattle: @ 829A715
	.string "I shouldn't have picked up…$"

Route114_Text_LucasIntro: @ 829A777
	.string "I know Basil in real life, so if I lose\n"
	.string "I can punch him!$"

Route114_Text_LucasDefeat: @ 829A7B5
	.string "Shoutout to Basil for being a \n"
	.string "mega-bitch.$"

Route114_Text_LucasPostBattle: @ 829A7D4
	.string "Shoutout to Basil for being a \n"
	.string "mega-bitch.$"

Route114_Text_ShaneIntro: @ 829A818
	.string "Alr, lemme spin my wheel real quick…\p"
	.string "Cool, got my team picked out.$"

Route114_Text_ShaneDefeat: @ 829A88F
	.string "Maybe I should just stick to one.$"

Route114_Text_ShanePostBattle: @ 829A89F
	.string "Maybe I should just stick to one.$"

Route114_Text_NancyIntro: @ 829A8D9
	.string "Hmm… Should I play Leif, Seliph, or\n"
	.string "some other Yellow deck?\p"
	.string "What? Pokémon?$"

Route114_Text_NancyDefeat: @ 829A90E
	.string "Man, Seliph would have won…$"

Route114_Text_NancyPostBattle: @ 829A916
	.string "Man, Seliph would have won…$"

Route114_Text_SteveIntro: @ 829A943
	.string "Joined amas, won that. Kinda done\n"
	.string "with Cipher now./p"
	.string "Maybe a Pokémon battle would be fun.$"

Route114_Text_SteveDefeat: @ 829A973
	.string "Good game.$"

Route114_Text_StevePostBattle: @ 829A981
	.string "Good game.$"

Route114_Text_SteveRegister: @ 829A9F7
	.string "Don't forget what you've done to me!\n"
	.string "I'll make it so you can't forget!$"

Route114_Text_SteveRematchIntro: @ 829AA3E
	.string "Ufufufufufu…\n"
	.string "Come on, battle my Pokémon…$"

Route114_Text_SteveRematchDefeat: @ 829AA67
	.string "I feel so lucky getting to see your\n"
	.string "Pokémon…$"

Route114_Text_StevePostRematch: @ 829AA94
	.string "Ufufufufufu…\p"
	.string "When I see Pokémon battling, I get all\n"
	.string "shivery and shaky…$"

Route114_Text_BernieIntro: @ 829AADB
	.string "Oh, I'm old am I? How about I break\n"
	.string "your kneecaps with my cane?$"

Route114_Text_BernieDefeat: @ 829AB1A
	.string "Well. Fuck.\p"

Route114_Text_BerniePostBattle: @ 829AB36
	.string "Wanna talk about Edelgard?\p"

Route114_Text_BernieRegister: @ 829ABA6
	.string "You set my spirit on fire.\n"
	.string "Let's register each other!$"

Route114_Text_BernieRematchIntro: @ 829ABDC
	.string "Have you learned to keep water handy\n"
	.string "for campfires?$"

Route114_Text_BernieRematchDefeat: @ 829AC10
	.string "I got hosed down before I could\n"
	.string "flare up, I guess.$"

Route114_Text_BerniePostRematch: @ 829AC43
	.string "You really do have to be careful with\n"
	.string "any sort of fire in a forest.\p"
	.string "Don't ever underestimate the power\n"
	.string "of fire.$"

Route114_Text_ClaudeIntro: @ 829ACB3
	.string "Ah, we meet again! I was just going\n"
	.string "to take a break from my book.\p"
	.string "Care for another battle?$"

Route114_Text_ClaudeDefeat: @ 829AD0A
	.string "You've got some serious potential!$"

Route114_Text_ClaudePostBattle: @ 829AD2E
	.string "You've got some serious potential!$"

Route114_Text_NolanIntro: @ 829ADA1
	.string "I've been on my own for two months\n"
	.string "and my roommate just made baked\p"
	.string "potatoes in his air fryer and I'm\n"
	.string "eating it like a corn on the cob.$"

Route114_Text_NolanDefeat: @ 829AE05
	.string "This is living.$"

Route114_Text_NolanPostBattle: @ 829AE3D
	.string "This is living.$"

Route114_Text_TyraIntro: @ 829AE96
	.string "Tyra: Well, sure.\n"
	.string "I'm in the mood for it.\l"
	.string "I'll teach you a little about Pokémon.$"

Route114_Text_TyraDefeat: @ 829AEE7
	.string "Tyra: What an amazing battle style!$"

Route114_Text_TyraPostBattle: @ 829AF0B
	.string "Tyra: I was teaching my junior Ivy\n"
	.string "about Pokémon.$"

Route114_Text_TyraNotEnoughMons: @ 829AF3D
	.string "Tyra: Giggle…\n"
	.string "If you want to battle with us, just one\l"
	.string "Pokémon isn't enough!$"

Route114_Text_IvyIntro: @ 829AF89
	.string "Ivy: Who taught you about Pokémon?$"

Route114_Text_IvyDefeat: @ 829AFAC
	.string "Ivy: What an amazing battle style!$"

Route114_Text_IvyPostBattle: @ 829AFCF
	.string "Ivy: I started training Pokémon\n"
	.string "because Tyra, my student mentor,\l"
	.string "taught me!$"

Route114_Text_IvyNotEnoughMons: @ 829B01B
	.string "Ivy: Do you only have one Pokémon?\n"
	.string "I think it must feel lonesome.$"

Route114_Text_KaiIntro: @ 829B05D
	.string "Ah did you message me about cards?\n"
	.string "Sorry, been away for a while!$"

Route114_Text_KaiDefeat: @ 829B089
	.string "Oh, it was just a battle.$"

Route114_Text_KaiPostBattle: @ 829B0B5
	.string "Oh, it was just a battle.$"

Route114_Text_CharlotteIntro: @ 829B0DB
	.string "I practiced a little bit and think\n"
	.string "I got better- mind if we battle again?$"

Route114_Text_CharlotteDefeat: @ 829B0FB
	.string "Dang, I'm still no good…$"

Route114_Text_CharlottePostBattle: @ 829B11A
	.string "Dang, I'm still no good…$"

Route114_Text_AngelinaIntro: @ 829B16F
	.string "So we meet again. Sorry about last\n"
	.string "time, usually all I get is requests\l"
	.string "for wording help…\p"
	.string "Oh by the way, you should try out\n"
	.string "Mono Chrom sometime- he's actually\l"
	.string "a really solid deck!\p"

Route114_Text_AngelinaDefeat: @ 829B19C
	.string "I almost won a major with him.\n"
	.string "Almost…$"

Route114_Text_AngelinaPostBattle: @ 829B1BC
	.string "I almost won a major with him.\n"
	.string "Almost…$"

Route115_Text_TimothyIntro: @ 829B1FA
	.string "Hm…\n"
	.string "You seem rather capable…\l"
	.string "Let me keep you company!$"

Route115_Text_TimothyDefeat: @ 829B230
	.string "You're much stronger than\n"
	.string "I'd imagined!$"

Route115_Text_TimothyPostBattle: @ 829B258
	.string "There is no such thing as a born genius.\n"
	.string "It all depends on effort!\l"
	.string "That is what I believe…$"

Route115_Text_TimothyRegister: @ 829B2B3
	.string "Hmm… A loss this thorough has been\n"
	.string "a distant memory.\p"
	.string "If you would allow it, I wish for\n"
	.string "another opportunity to do battle.$"

Route115_Text_TimothyRematchIntro: @ 829B32C
	.string "Hm… As always, your agility speaks\n"
	.string "for itself.\l"
	.string "Come, keep me company!$"

Route115_Text_TimothyRematchDefeat: @ 829B372
	.string "As strong as ever!$"

Route115_Text_TimothyPostRematch: @ 829B385
	.string "All it takes is effort!\p"
	.string "I lost because I haven't put in enough\n"
	.string "effort!$"

Route115_Text_KoichiIntro: @ 829B3CC
	.string "Huh? Who're you?\n"
	.string "Eh whatever, let's fuckin' FIGHT!$"
	.string "Damn, ggs.$"

Route115_Text_KoichiDefeat: @ 829B3ED
	.string "Damn, ggs.$"

Route115_Text_KoichiPostBattle: @ 829B3FF
	.string "Damn, ggs.$"

Route115_Text_NobIntro: @ 829B449
	.string "Between collecting and getting into\n"
	.string "HSR, my wallet is really hurting…$"

Route115_Text_NobDefeat: @ 829B480
	.string "Oof, right in the wallet…$"

Route115_Text_NobPostBattle: @ 829B49D
	.string "Oof, right in the wallet…$"

Route115_Text_NobRegister: @ 829B50B
	.string "You impress me! Give me a rematch\n"
	.string "after I redo my training!$"

Route115_Text_NobRematchIntro: @ 829B547
	.string "After you beat me, we trained hard to\n"
	.string "improve our skills.\l"
	.string "Come on, give us a rematch!$"

Route115_Text_NobRematchDefeat: @ 829B59D
	.string "Ugwaaah!\n"
	.string "We lost again!$"

Route115_Text_NobPostRematch: @ 829B5B5
	.string "My Pokémon will grow stronger!\n"
	.string "I'll redouble my training!$"

Route115_Text_CyndyIntro: @ 829B5EF
	.string "What're you looking for? I've got\n"
	.string "some ST+, some singles, some stuff\l"
	.string "I'm not selling…$"

Route115_Text_CyndyDefeat: @ 829B62D
	.string "Oh, I've got Pokémon cards too!$"

Route115_Text_CyndyPostBattle: @ 829B647
	.string "Oh, I've got Pokémon cards too!$"

Route115_Text_CyndyRegister: @ 829B6AB
	.string "Okay, fine, you're free to come here.\n"
	.string "In return, I'd like to battle you again.$"

Route115_Text_CyndyRematchIntro: @ 829B6FA
	.string "Okay, let's get this battle on!$"

Route115_Text_CyndyRematchDefeat: @ 829B71A
	.string "I can battle but my Pokémon…$"

Route115_Text_CyndyPostRematch: @ 829B737
	.string "Even when I lose, I still get some\n"
	.string "enjoyment out of it.\l"
	.string "It must be that I love Pokémon.$"

Route115_Text_HectorIntro: @ 829B78F
	.string "Fallen Edelgard, fallen Dimitri,\n"
	.string "when do we get fallen Claude???$"

Route115_Text_HectorDefeat: @ 829B7C5
	.string "FEH can be so cruel…$"

Route115_Text_HectorPostBattle: @ 829B7EA
	.string "FEH can be so cruel…$"

Route115_Text_KyraIntro: @ 829B826
	.string "You might have gotten me last time,\n"
	.string "but I'll win this time for sure!$"

Route115_Text_KyraDefeat: @ 829B85D
	.string "Mods, send this guy to the principal's\n"
	.string "office and HAVE HIM CLOWNED!$"

Route115_Text_KyraPostBattle: @ 829B869
	.string "Mods, send this guy to the principal's\n"
	.string "office and HAVE HIM CLOWNED!$"

Route115_Text_JaidenIntro: @ 829B8C1
	.string "Tbh I just joined for D&D.$"

Route115_Text_JaidenDefeat: @ 829B8E8
	.string "Oh well, might go play some Dune.$"

Route115_Text_JaidenPostBattle: @ 829B904
	.string "Oh well, might go play some Dune.$"

Route115_Text_HeleneIntro: @ 829B92D
	.string "I haven't bought any Pokémon DLC,\n"
	.string "haven't really liked the games lately.$"

Route115_Text_HeleneDefeat: @ 829B958
	.string "I did, however, spend 80 dollars for\n"
	.string "DLC in a GOOD game- SoV.$"

Route115_Text_HelenePostBattle: @ 829B971
	.string "I did, however, spend 80 dollars for\n"
	.string "DLC in a GOOD game- SoV.$"

Route115_Text_AlixIntro: @ 829B9CB
	.string "Our eyes met!\n"
	.string "There's no getting away now!$"

Route115_Text_AlixDefeat: @ 829B9F6
	.string "Gah!\n"
	.string "Not bad!$"

Route115_Text_AlixPostBattle: @ 829BA04
	.string "Oh, well.\n"
	.string "I think I will Teleport home.$"

Route115_Text_MarleneIntro: @ 829BA2C
	.string "Hey you should play Eternal\n"
	.string "Return.$"

Route115_Text_MarleneDefeat: @ 829BA67
	.string "But I even have a gif to\n"
	.string "convince you…$"

Route115_Text_MarlenePostBattle: @ 829BA87
	.string "But I even have a gif to\n"
	.string "convince you…$"

Route116_Text_ClarkIntro: @ 829BACD
	.string "I'm using tilt controls!$"

Route116_Text_ClarkDefeat: @ 829BB0F
	.string "I'm using tilt controls!$"

Route116_Text_ClarkPostBattle: @ 829BB31
	.string "I'm using tilt controls!$"

Route116_Text_JoeyIntro: @ 829BB79
	.string "They actually buffed some cool Pokémon\n"
	.string "in this game!$"

Route116_Text_JoeyDefeat: @ 829BB9A
	.string "Maybe I should have used some of them…$"

Route116_Text_JoeyPostBattle: @ 829BBC6
	.string "Back to shiny hunting, I guess…$"

Route116_Text_JoseIntro: @ 829BBFD
	.string "If I had a dime for every emote I was\n"
	.string "in about strangulation, I would have\l"
	.string "2 dimes.$"

Route116_Text_JoseDefeat: @ 829BC25
	.string "It's strange it happened twice, right?$"

Route116_Text_JosePostBattle: @ 829BC42
	.string "It's strange it happened twice, right?$"

Route116_Text_JaniceIntro: @ 829BC7F
	.string "I'm on a very sane and normal quest\n"
	.string "to collect ALL the Lyn merchandise.$"

Route116_Text_JaniceDefeat: @ 829BCB3
	.string "I needed that money for a playmat…$"

Route116_Text_JanicePostBattle: @ 829BCCC
	.string "I needed that money for a playmat…$"

Route116_Text_JerryIntro: @ 829BD0C
	.string "Hopefully I don't disconnect during\n"
	.string "our battle!$"

Route116_Text_JerryDefeat: @ 829BD66
	.string "…ohhh nooo I'm breaking up…$"

Route116_Text_JerryPostBattle: @ 829BD92
	.string "…ohhh nooo I'm breaking up…$"

Route116_Text_JerryRegister1: @ 829BDEF
	.string "I learned at the Trainer's School\n"
	.string "that a PokéNav can register Trainers.\p"
	.string "I don't really get what that means,\n"
	.string "so can I just try it?$"

Route116_Text_JerryRegister2: @ 829BE71
	.string "I learned at the Trainer's School\n"
	.string "that a PokéNav can register Trainers.\p"
	.string "I don't really get what that means,\n"
	.string "so can I just try it?$"

Route116_Text_JerryRematchIntro: @ 829BEF3
	.string "I've been studying seriously at the\n"
	.string "Trainer's School.\l"
	.string "I won't lose like I did last time.$"

Route116_Text_JerryRematchDefeat: @ 829BF4C
	.string "Hunh?\n"
	.string "I studied diligently.$"

Route116_Text_JerryPostRematch: @ 829BF68
	.string "I'll have to redo some courses at\n"
	.string "the Trainer's School.\l"
	.string "If I don't, Roxanne will be steamed.$"

Route116_Text_KarenIntro: @ 829BFC5
	.string "I study at school, and I study on\n"
	.string "the way home, too!$"

Route116_Text_KarenDefeat: @ 829BFFA
	.string "I'm in shock--I lost?$"

Route116_Text_KarenPostBattle: @ 829C010
	.string "Awww, I'll never become an elegant\n"
	.string "Trainer like Roxanne this way!$"

Route116_Text_KarenRegister1: @ 829C052
	.string "Oh, wow! Isn't that a PokéNav?\n"
	.string "I have one, too! Please register me!$"

Route116_Text_KarenRegister2: @ 829C096
	.string "Oh, wow! Isn't that a PokéNav?\n"
	.string "I have one, too! Please register me!$"

Route116_Text_KarenRematchIntro: @ 829C0DA
	.string "I studied a whole lot since I saw you.\n"
	.string "You must see my achievements!$"

Route116_Text_KarenRematchDefeat: @ 829C11F
	.string "I'm in shock.\n"
	.string "I lost again?$"

Route116_Text_KarenPostRematch: @ 829C13B
	.string "You've beaten Roxanne?\n"
	.string "I can't beat you, then. Not yet.$"

Route116_Text_SarahIntro: @ 829C173
	.string "Oh? You're approaching me?\n"
	.string "The worlds biggest Sinnoh stan??$"

Route116_Text_SarahDefeat: @ 829C1B8
	.string "But… my Sinnoh Pokémon…$"

Route116_Text_SarahPostBattle: @ 829C1EA
	.string "But… my Sinnoh Pokémon…$"

Route116_Text_DawsonIntro: @ 829C266
	.string "Hmm… Which Sanaki build should I run?$"

Route116_Text_DawsonDefeat: @ 829C2C2
	.string "Wait, this isn't Cipher?$"

Route116_Text_DawsonPostBattle: @ 829C2DD
	.string "Wait, this isn't Cipher?$"

Route116_Text_DevanIntro: @ 829C350
	.string "We'll rock you hard!$"

Route116_Text_DevanDefeat: @ 829C365
	.string "Aiyiyi!\n"
	.string "No contest at all!$"

Route116_Text_DevanPostBattle: @ 829C380
	.string "I should try different Pokémon\n"
	.string "types, that's what I ought to do.$"

Route116_Text_JohnsonIntro: @ 829C3C1
	.string "I guess I can take a break from\n"
	.string "carrying CS01 to battle.$"

Route116_Text_JohnsonDefeat: @ 829C3F7
	.string "That was fun even though I lost.$"

Route116_Text_JohnsonPostBattle: @ 829C418
	.string "That was fun even though I lost.$"

Route117_Text_IsaacIntro: @ 829C43F
	.string "Ok. Let's see if Basil's any good at\n"
	.string "game design.$"

Route117_Text_IsaacDefeat: @ 829C47A
	.string "Damn this hack sucks.$"

Route117_Text_IsaacPostBattle: @ 829C498
	.string "Damn this hack sucks.$"

Route117_Text_IsaacRegister: @ 829C508
	.string "Damn this hack sucks.$"

Route117_Text_IsaacRematchIntro: @ 829C549
	.string "The Pokémon I've been raising are\n"
	.string "looking good, just like before.$"

Route117_Text_IsaacRematchDefeat: @ 829C58B
	.string "You know how to raise them properly.\n"
	.string "You might have Day Care skills…$"

Route117_Text_IsaacPostRematch: @ 829C5D0
	.string "Your Pokémon are growing good!\n"
	.string "You should enter them in Contests.$"

Route117_Text_LydiaIntro: @ 829C612
	.string "Please, allow me to evaluate if you\n"
	.string "have raised your Pokémon properly.$"

Route117_Text_LydiaDefeat: @ 829C659
	.string "Yes, they are growing properly.$"

Route117_Text_LydiaPostBattle: @ 829C679
	.string "Try raising Pokémon with more\n"
	.string "attention to their character traits.$"

Route117_Text_LydiaRegister: @ 829C6BC
	.string "I'm glad I met a superb Trainer in you.\n"
	.string "I hope to see you again.$"

Route117_Text_LydiaRematchIntro: @ 829C6FD
	.string "Allow me to reevaluate if you have\n"
	.string "raised your Pokémon properly.$"

Route117_Text_LydiaRematchDefeat: @ 829C73E
	.string "They are growing admirably.$"

Route117_Text_LydiaPostRematch: @ 829C75A
	.string "Pokémon seem to like different kinds\n"
	.string "of {POKEBLOCK}S, depending on their nature.$"

Route117_Text_DylanIntro: @ 829C7A5
	.string "I wonder if I could stream this battle…$"

Route117_Text_DylanDefeat: @ 829C7EB
	.string "Check out our Twitch- SaltCommittee!$"

Route117_Text_DylanPostBattle: @ 829C800
	.string "Check out our Twitch- SaltCommittee!$"

Route117_Text_DylanRegister: @ 829C846
	.string "Pokémon have to be strong, too?\n"
	.string "I'd like you to train me!$"

Route117_Text_DylanRematchIntro: @ 829C880
	.string "I'm smack in the middle of a triathlon,\n"
	.string "but I'm comfortably ahead.\l"
	.string "Let's make this a quick battle!$"

Route117_Text_DylanRematchDefeat: @ 829C8E3
	.string "I ran out of energy again!$"

Route117_Text_DylanPostRematch: @ 829C8FE
	.string "I was tops in swimming and cycling,\n"
	.string "but I'm not quite that confident with\l"
	.string "Pokémon yet.$"

Route117_Text_MariaIntro: @ 829C955
	.string "Did you know there's a censored Pokémon\n"
	.string "card?$"

Route117_Text_MariaDefeat: @ 829C9A6
	.string "It might have to do with one of the\n"
	.string "Pokémon on my team.$"

Route117_Text_MariaPostBattle: @ 829C9D0
	.string "It might have to do with one of the\n"
	.string "Pokémon on my team.$"

Route117_Text_MariaRegister: @ 829CA32
	.string "You appear to be training properly…\n"
	.string "If you'd like, I'll battle you later!$"

Route117_Text_MariaRematchIntro: @ 829CA7C
	.string "Are you keeping up with your training?\n"
	.string "I sure am!\l"
	.string "Let me show you the evidence!$"

Route117_Text_MariaRematchDefeat: @ 829CACC
	.string "I need to get more practices in,\n"
	.string "I guess.$"

Route117_Text_MariaPostRematch: @ 829CAF6
	.string "I'll resume training tomorrow.\n"
	.string "Let's battle again sometime!$"

Route117_Text_DerekIntro: @ 829CB32
	.string "You'll never guess my favorites.$"

Route117_Text_DerekDefeat: @ 829CB87
	.string "Dogs are so cool.$"

Route117_Text_DerekPostBattle: @ 829CBAD
	.string "Dogs are so cool.$"

Route117_Text_AnnaIntro: @ 829CC4A
	.string "Anna: I'm with my pretty junior student\n"
	.string "partner. I have to do good!$"

Route117_Text_AnnaDefeat: @ 829CC8E
	.string "Anna: I'm with my pretty junior student\n"
	.string "partner! Let me win!$"

Route117_Text_AnnaPostBattle: @ 829CCCB
	.string "Anna: Your Pokémon have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaAndMegRegister: @ 829CD1D
	.string "Anna: We can't take this lying down!\n"
	.string "You will come back, won't you?$"

Route117_Text_AnnaNotEnoughMons: @ 829CD61
	.string "Anna: If you want to battle us,\n"
	.string "bring two Pokémon with you.$"

Route117_Text_MegIntro: @ 829CD9D
	.string "48 65 6C 6C 6F 2C 20 57 65 6C 63 6F 6D\n"
	.string "65 20 74 6F 20 43 69 70 68 65 72 63 6F\p"
	.string "72 64 21 20$"

Route117_Text_MegDefeat: @ 829CDE9
	.string "49 20 68 61 76 65 20 6C 6F 73 74$"

Route117_Text_MegPostBattle: @ 829CE17
	.string "49 20 68 61 76 65 20 6C 6F 73 74$"

Route117_Text_MegNotEnoughMons: @ 829CE52
	.string "59 6F 75 20 6E 65 65 64 20 6D 75 6C 74\n"
	.string "69 70 6C 65 20 70 6F 6B 65 6D 6F 6E$"

Route117_Text_AnnaRematchIntro: @ 829CEB6
	.string "Anna: I can't keep losing in front of\n"
	.string "my junior partner, right?$"

Route117_Text_AnnaRematchDefeat: @ 829CEF6
	.string "Anna: I couldn't get into the groove.$"

Route117_Text_AnnaPostRematch: @ 829CF1C
	.string "Anna: Your Pokémon have some good\n"
	.string "combinations.\p"
	.string "I'd say you're second only to us!$"

Route117_Text_AnnaRematchNotEnoughMons: @ 829CF6E
	.string "Anna: If you want to battle us,\n"
	.string "bring two Pokémon with you.$"

Route117_Text_MegRematchIntro: @ 829CFAA
	.string "Meg: I'm going to tag up with my\n"
	.string "senior partner and win this time!$"

Route117_Text_MegRematchDefeat: @ 829CFED
	.string "Meg: Too strong!$"

Route117_Text_MegPostRematch: @ 829CFFE
	.string "Meg: I battled together with my\n"
	.string "senior partner, but we lost…\p"
	.string "That's so discouraging…$"

Route117_Text_MegRematchNotEnoughMons: @ 829D053
	.string "Meg: Do you only have one Pokémon?\n"
	.string "We can't battle with you, then.\p"
	.string "We want to have a 2-on-2 battle.$"

Route117_Text_MelinaIntro: @ 829D0B7
	.string "I aspire to live up to my name.$"

Route117_Text_MelinaDefeat: @ 829D0F1
	.string "Seems like I need to play more.$"

Route117_Text_MelinaPostBattle: @ 829D10E
	.string "Seems like I need to play more.$"

Route117_Text_BrandiIntro: @ 829D14B
	.string "Is Keaton in this game?$"

Route117_Text_BrandiDefeat: @ 829D189
	.string "I just miss him.$"

Route117_Text_BrandiPostBattle: @ 829D196
	.string "I just miss him.$"

Route117_Text_AishaIntro: @ 829D1D1
	.string "Tbh I just joined for D&D.$"

Route117_Text_AishaDefeat: @ 829D206
	.string "Oh well, might go play some Dune.$"

Route117_Text_AishaPostBattle: @ 829D24C
	.string "Oh well, might go play some Dune.$"

Route118_Text_RoseIntro: @ 829D290
	.string "I don't really know how I got in\n"
	.string "this hack tbh.$"

Route118_Text_RoseDefeat: @ 829D2D8
	.string "I should probably go find Vance…$"

Route118_Text_RosePostBattle: @ 829D2FA
	.string "I should probably go find Vance…$"

Route118_Text_RoseRegister: @ 829D343
	.string "Sniff… That odor--it's a PokéNav!\n"
	.string "We must register each other!$"

Route118_Text_RoseRematchIntro: @ 829D382
	.string "Were you drawn here by the sweet\n"
	.string "aroma?$"

Route118_Text_RoseRematchDefeat: @ 829D3AA
	.string "The power of aroma…\n"
	.string "It didn't seem to do much.$"

Route118_Text_RosePostRematch: @ 829D3D9
	.string "If you use a sweet aroma properly,\n"
	.string "Pokémon will be attracted by it.$"

Route118_Text_PerryIntro: @ 829D41D
	.string "OHKO moves are great- just hit the\n"
	.string "30%!$"

Route118_Text_PerryDefeat: @ 829D45B
	.string "Sadly I was not given any OHKO moves…$"

Route118_Text_PerryPostBattle: @ 829D46C
	.string "Sadly I was not given any OHKO moves…$"

Route118_Text_ChesterIntro: @ 829D4A6
	.string "Its sad I'm most known for being\n"
	.string "hated so much by Rotten.$"

Route118_Text_ChesterDefeat: @ 829D4C4
	.string "Seriously, that guy needs help.$"

Route118_Text_ChesterPostBattle: @ 829D4DA
	.string "Seriously, that guy needs help.$"

Route118_Text_BarnyIntro: @ 829D515
	.string "Oh hi, I'm Nex. Usually I pop into\n"
	.string "General every once in a while, but\p"
	.string "I can only deal with Ciphercord in\n"
	.string "small doses.$"

Route118_Text_BarnyDefeat: @ 829D55C
	.string "Ciphercord really is goofy…$"

Route118_Text_BarnyPostBattle: @ 829D587
	.string "Ciphercord really is goofy…$"

Route118_Text_WadeIntro: @ 829D5DF
	.string "For Fishermen, equipment is the key.\p"
	.string "But for Trainers, the key ingredients\n"
	.string "are Pokémon and heart, of course!$"

Route118_Text_WadeDefeat: @ 829D64C
	.string "I was beaten in heart?$"

Route118_Text_WadePostBattle: @ 829D663
	.string "Come to think of it, fishing is a battle\n"
	.string "between a Fisherman and a Pokémon.$"

Route118_Text_DaltonIntro: @ 829D6AF
	.string "Let my melody rock your soul!$"

Route118_Text_DaltonDefeat: @ 829D6CD
	.string "La-lalala…$"

Route118_Text_DaltonPostBattle: @ 829D6D8
	.string "An electric guitar doesn't always\n"
	.string "have to be noisy…\p"
	.string "It can be strummed to squeeze out\n"
	.string "this heart-stirring melody…$"

Route118_Text_DaltonRegister: @ 829D74A
	.string "When I compose better melodies,\n"
	.string "you have to come listen, okay?$"

Route118_Text_DaltonRematchIntro: @ 829D789
	.string "A melody from my Pokémon and me…\n"
	.string "Let us deliver it to your soul.$"

Route118_Text_DaltonRematchDefeat: @ 829D7CA
	.string "La-lalala…$"

Route118_Text_DaltonPostRematch: @ 829D7D5
	.string "When I play, my emotions should reach\n"
	.string "you through my electric guitar…$"

Route118_Text_DeandreIntro: @ 829D81B
	.string "I got clowned for messing up the count\n"
	.string "so long ago…$"

Route118_Text_DeandreDefeat: @ 829D83C
	.string "Some day the mods might remove it…$"

Route118_Text_DeandrePostBattle: @ 829D872
	.string "Some day the mods might remove it…$"

Route119_Text_BrentIntro: @ 829D8C2
	.string "Why are you bothering me all the way\n"
	.string "out here? I'm supposed to be retired.\p"
	.string "I have my blue name already!$"

Route119_Text_BrentDefeat: @ 829D8F0
	.string "Damn. Sacced again.$"

Route119_Text_BrentPostBattle: @ 829D902
	.string "Damn. Sacced again.$"

Route119_Text_DonaldIntro: @ 829D941
	.string "Sometimes, when I feel like being a\n"
	.string "gremlin, I play Sword Aggro.$"

Route119_Text_DonaldDefeat: @ 829D97C
	.string "What? No, I was talking about\n"
	.string "Shadowverse ladder, not Cipher.$"

Route119_Text_DonaldPostBattle: @ 829D993
	.string "What? No, I was talking about\n"
	.string "Shadowverse ladder, not Cipher.$"

Route119_Text_TaylorIntro: @ 829D9CD
	.string "Aatrox is so cool.\p"
	.string "League? Hell no, talking about LoR.$"

Route119_Text_TaylorDefeat: @ 829DA14
	.string "I would never play League…$"

Route119_Text_TaylorPostBattle: @ 829DA2C
	.string "I would never play League…$"

Route119_Text_DougIntro: @ 829DA7D
	.string "A new Fire Emblem figure is coming\n"
	.string "out, so I need this money.$"

Route119_Text_DougDefeat: @ 829DABC
	.string "Well, guess I can not eat instead.$"

Route119_Text_DougPostBattle: @ 829DADB
	.string "Well, guess I can not eat instead.$"

Route119_Text_GregIntro: @ 829DB17
	.string "Sip emotes are the best.$"

Route119_Text_GregDefeat: @ 829DB66
	.string "You can't react to me with sip\n"
	.string "emotes though- I'll block you.$"

Route119_Text_GregPostBattle: @ 829DB7C
	.string "You can't react to me with sip\n"
	.string "emotes though- I'll block you.$"

Route119_Text_KentIntro: @ 829DBC2
	.string "I might be the only Nowi player on\n"
	.string "the server, and not won very much with\l"
	.string "her, but I swear she's not that bad!$"

Route119_Text_KentDefeat: @ 829DC20
	.string "Look I'll just pass you my red blue\n"
	.string "and yellow list to get you started.$"

Route119_Text_KentPostBattle: @ 829DC2B
	.string "Look I'll just pass you my red blue\n"
	.string "and yellow list to get you started.$"

Route119_Text_JacksonIntro: @ 829DC4C
	.string "The ROM hack creator let me have a\n"
	.string "level 100 Pokémon! I can't lose!$"

Route119_Text_JacksonDefeat: @ 829DC9F
	.string "Heh, I just thought it'd be funny.$"

Route119_Text_JacksonPostBattle: @ 829DCC6
	.string "Heh, I just thought it'd be funny.$"

Route119_Text_JacksonRegister: @ 829DD1C
	.string "I hope you'll give me a rematch without\n"
	.string "mocking my lack of knowledge.$"

Route119_Text_JacksonRematchIntro: @ 829DD62
	.string "I'm going to regain my wild spirit by\n"
	.string "being together with Pokémon.$"

Route119_Text_JacksonRematchDefeat: @ 829DDA5
	.string "You've remained strong!$"

Route119_Text_JacksonPostRematch: @ 829DDBD
	.string "Believe in your Pokémon.\n"
	.string "Believe in yourself.\p"
	.string "The road will reveal itself to you.$"

Route119_Text_CatherineIntro: @ 829DE0F
	.string "Man, FEH has gotten so ridiculous.\p"
	.string "I saw the warning signs when they\n"
	.string "started giving armors insane stats.$"

Route119_Text_CatherineDefeat: @ 829DE5D
	.string "Then Wind Claude came out, now I \n"
	.string "don't want to touch the game again.$"

Route119_Text_CatherinePostBattle: @ 829DE88
	.string "Then Wind Claude came out, now I \n"
	.string "don't want to touch the game again.$"

Route119_Text_CatherineRegister: @ 829DEF7
	.string "Do you have a PokéNav?\n"
	.string "It's a must-have tool for any Trainer.\p"
	.string "Oh, you do have one!\n"
	.string "Let's register each other, then!$"

Route119_Text_CatherineRematchIntro: @ 829DF6B
	.string "How's your journey with Pokémon\n"
	.string "going?$"

Route119_Text_CatherineRematchDefeat: @ 829DF92
	.string "I'm still missing something…$"

Route119_Text_CatherinePostRematch: @ 829DFAF
	.string "In the same way that you, as a Trainer,\n"
	.string "rely on your Pokémon, your Pokémon\l"
	.string "rely on you.$"

Route119_Text_HughIntro: @ 829E007
	.string "Hello. I played in AMAs once, but now\p"
	.string "I mostly just play DnD."$"

Route119_Text_HughDefeat: @ 829E063
	.string "When I did play Cipher, Thia taught me\n"
	.string "some stall and it was a joy.$"

Route119_Text_HughPostBattle: @ 829E071
	.string "When I did play Cipher, Thia taught me\n"
	.string "some stall and it was a joy.$"

Route119_Text_PhilIntro: @ 829E0A5
	.string "I've been on the customs grind-\n"
	.string "Come see what I've been cooking!$"

Route119_Text_PhilDefeat: @ 829E0E1
	.string "Brazil Volke is peak, if you play\n"
	.string "customs you should try it.$"

Route119_Text_PhilPostBattle: @ 829E0F6
	.string "Brazil Volke is peak, if you play\n"
	.string "customs you should try it.$"

Route119_Text_YasuIntro: @ 829E134
	.string "Honestly, being a mod in Ciphercord\n"
	.string "isn't that bad. Granted, I was a mod\l"
	.string "on the Smogon forums, and uh…\p"
	.string "That was a whole other level.$"

Route119_Text_YasuDefeat: @ 829E18D
	.string "One standout was the guy who said\n"
	.string "autistic women had bigger boobs.\p"
	.string "He said he wasn't going to listen\n"
	.string "to me since I had a Camilla pfp.$"

Route119_Text_YasuPostBattle: @ 829E19D
	.string "One standout was the guy who said\n"
	.string "autistic women had bigger boobs.\p"
	.string "He said he wasn't going to listen\n"
	.string "to me since I had a Camilla pfp.$"

Route119_Text_TakashiIntro: @ 829E1F5
	.string "I've got a couple SR+ pair arts\n"
	.string "collected- they look so good.$"

Route119_Text_TakashiDefeat: @ 829E22B
	.string "Now I need to save up for Lilina+\n"
	.string "to go with my Roy…$"

Route119_Text_TakashiPostBattle: @ 829E245
	.string "Now I need to save up for Lilina+\n"
	.string "to go with my Roy…$"

Route119_Text_HideoIntro: @ 829E26A
	.string "By the way, did you know Brainiac\n"
	.string "wanted the Champion to have all megas?\p"
	.string "I fought tooth and nail against that,\n"
	.string "and we reached a compromise.$"

Route119_Text_HideoDefeat: @ 829E288
	.string "You're welcome, by the way.$"

Route119_Text_HideoPostBattle: @ 829E2A3
	.string "You're welcome, by the way.$"

Route119_Text_ChrisIntro: @ 829E30D
	.string "You spoke to me…\n"
	.string "So you want to challenge me!\p"
	.string "Sure! I'll try out the Pokémon I caught\n"
	.string "while Surfing!$"

Route119_Text_ChrisDefeat: @ 829E372
	.string "I don't have a clue about what it\n"
	.string "takes to win.$"

Route119_Text_ChrisPostBattle: @ 829E3A2
	.string "Go for a Surf on my Pokémon…\p"
	.string "Then fish off its back…\p"
	.string "It's an indescribably luxuriant moment!$"

Route119_Text_FabianIntro: @ 829E3FF
	.string "I think I'm one of the only people who's\n"
	.string "been into customs for a long time and\l"
	.string "still doesn't have a set out.$"

Route119_Text_FabianDefeat: @ 829E44F
	.string "LU01 will come out… some day.$"

Route119_Text_FabianPostBattle: @ 829E492
	.string "LU01 will come out… some day.$"

Route119_Text_DaytonIntro: @ 829E4DF
	.string "I don't play Cipher nowadays, but\n"
	.string "I still like to draw a FE character\l"
	.string "every once in a while!$"

Route119_Text_DaytonDefeat: @ 829E513
	.string "Come check out the art channel-\n"
	.string "Lots of people working hard there!$"

Route119_Text_DaytonPostBattle: @ 829E532
	.string "Come check out the art channel-\n"
	.string "Lots of people working hard there!$"

Route119_Text_RachelIntro: @ 829E56F
	.string "I got clowned for messing up the count\n"
	.string "so long ago…$"

Route119_Text_RachelDefeat: @ 829E5B1
	.string "Some day the mods might remove it…$"

Route119_Text_RachelPostBattle: @ 829E5CB
	.string "Some day the mods might remove it…$"

Route120_Text_ColinIntro: @ 829E62D
	.string "Do you have any moves that can strike\n"
	.string "a flying Pokémon?$"

Route120_Text_ColinDefeat: @ 829E665
	.string "You soared above me!$"

Route120_Text_ColinPostBattle: @ 829E67A
	.string "The move Fly is convenient,\n"
	.string "don't you think?\p"
	.string "While the Pokémon is flying,\n"
	.string "almost no moves can strike it.$"

Route120_Text_RobertIntro: @ 829E6E3
	.string "I've got a decent collection of\n"
	.string "playmats, even some rare Cipher ones.$"

Route120_Text_RobertDefeat: @ 829E70A
	.string "Have I mentioned I absolutely hate how\n"
	.string "Fire Emblem mats are smaller?$"

Route120_Text_RobertPostBattle: @ 829E726
	.string "Have I mentioned I absolutely hate how\n"
	.string "Fire Emblem mats are smaller?$"

Route120_Text_RobertRegister: @ 829E75D
	.string "You can be counted on to get better.\n"
	.string "I'd like to register you in my PokéNav!$"

Route120_Text_RobertRematchIntro: @ 829E7AA
	.string "A Pokémon that grows steadily is one\n"
	.string "you can count on.$"

Route120_Text_RobertRematchDefeat: @ 829E7E1
	.string "Your Pokémon are seriously strong.$"

Route120_Text_RobertPostRematch: @ 829E804
	.string "My Pokémon are growing stronger.\n"
	.string "I have to grow stronger, too.$"

Route120_Text_LorenzoIntro: @ 829E843
	.string "I'll check your Pokémon and see if\n"
	.string "they're fit for the outdoors.$"

Route120_Text_LorenzoDefeat: @ 829E884
	.string "With Pokémon that strong, you're in\n"
	.string "no danger of needing rescue!$"

Route120_Text_LorenzoPostBattle: @ 829E8C5
	.string "To travel wherever your heart desires\n"
	.string "with Pokémon…\l"
	.string "That's the joy of being a Trainer.$"

Route120_Text_JennaIntro: @ 829E91C
	.string "How's your physical fitness?\n"
	.string "If you're not fit, you could have a\l"
	.string "rough time in critical situations.$"

Route120_Text_JennaDefeat: @ 829E980
	.string "I'm totally fit, but…$"

Route120_Text_JennaPostBattle: @ 829E996
	.string "Fitness training is in my routine.\n"
	.string "I always run with my Pokémon.$"

Route120_Text_JeffreyIntro: @ 829E9D7
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle?$"

Route120_Text_JeffreyDefeat: @ 829E9FF
	.string "Lost it…$"

Route120_Text_JeffreyPostBattle: @ 829EA08
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…$"

Route120_Text_JeffreyRegister: @ 829EA31
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Do you have a PokéNav…?$"

Route120_Text_JeffreyRematchIntro: @ 829EA61
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Want to battle again?$"

Route120_Text_JeffreyRematchDefeat: @ 829EA8F
	.string "… … … … … …\n"
	.string "I lost again…$"

Route120_Text_JeffreyPostRematch: @ 829EAA9
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "I'll try harder…\l"
	.string "For my precious Bug Pokémon…$"

Route120_Text_JenniferIntro: @ 829EAEF
	.string "Pokémon have many special abilities.\n"
	.string "If you want to become a first-class\l"
	.string "Trainer, learn about them.$"

Route120_Text_JenniferDefeat: @ 829EB53
	.string "You're obviously thinking.$"

Route120_Text_JenniferPostBattle: @ 829EB6E
	.string "The special abilities of Pokémon\n"
	.string "will make battle styles change.$"

Route120_Text_ChipIntro: @ 829EBAF
	.string "Who might you be?\p"
	.string "Are you perhaps searching for ancient\n"
	.string "ruins that are rumored to possibly\l"
	.string "exist according to legend?$"

Route120_Text_ChipDefeat: @ 829EC25
	.string "What a disgraceful setback…$"

Route120_Text_ChipPostBattle: @ 829EC41
	.string "That giant rock… I would like to\n"
	.string "believe it may indeed contain ancient\l"
	.string "ruins. But I see no entrance.$"

Route120_Text_ClarissaIntro: @ 829ECA6
	.string "If you see any Deirdre SR+ cards for\n"
	.string "sale anywhere, I call dibs!$"

Route120_Text_ClarissaDefeat: @ 829ECEF
	.string "There's no such thing as too many\n"
	.string "Deirdres…$"

Route120_Text_ClarissaPostBattle: @ 829ED19
	.string "There's no such thing as too many\n"
	.string "Deirdres…$"

Route120_Text_AngelicaIntro: @ 829ED71
	.string "Me, Pokémon, and my parasol…\p"
	.string "If any one of them is missing,\n"
	.string "the picture of beauty will be ruined.$"

Route120_Text_AngelicaDefeat: @ 829EDD3
	.string "You've completely ruined my beauty…$"

Route120_Text_AngelicaPostBattle: @ 829EDF7
	.string "A parasol wouldn't suit you at all.\p"
	.string "Why, something like this would only\n"
	.string "get in your way.$"

Route120_Text_KeigoIntro: @ 829EE50
	.string "I will adopt the movements of Pokémon\n"
	.string "and create new ninja techniques.$"

Route120_Text_KeigoDefeat: @ 829EE97
	.string "The creation of new ninja techniques\n"
	.string "is but a distant dream…$"

Route120_Text_KeigoPostBattle: @ 829EED4
	.string "Perhaps I ought to apprentice under\n"
	.string "a ninja sensei.$"

Route120_Text_RileyIntro: @ 829EF08
	.string "We ninja conceal ourselves under our\n"
	.string "camouflage cloaks.\l"
	.string "I bet you didn't know where I was!$"

Route120_Text_RileyDefeat: @ 829EF63
	.string "I lost!\n"
	.string "I should camouflage my shame!$"

Route120_Text_RileyPostBattle: @ 829EF89
	.string "Our camouflage cloaks are all\n"
	.string "handmade.$"

Route120_Text_CallieIntro: @ 829EFB1
	.string "If you don't pay attention,\n"
	.string "you could get hurt!$"

Route120_Text_CallieDefeat: @ 829EFE1
	.string "Ouch!\n"
	.string "I was the one to get hurt.$"

Route120_Text_CalliePostBattle: @ 829F002
	.string "I wonder… Should I evolve my Pokémon?\n"
	.string "They're cute the way they are, though.$"

Route120_Text_LeonelIntro: @ 829F04F
	.string "Your party Pokémon…\n"
	.string "Do you have different types?$"

Route120_Text_LeonelDefeat: @ 829F080
	.string "I've seen your policy in action!$"

Route120_Text_LeonelPostBattle: @ 829F0A1
	.string "I think it's awesome you're so strong\n"
	.string "battling with your favorite Pokémon.$"

Route121_Text_VanessaIntro: @ 829F0EC
	.string "Will you play with my delightfully\n"
	.string "pretty Pokémon?$"

Route121_Text_VanessaDefeat: @ 829F11F
	.string "This isn't what I meant!$"

Route121_Text_VanessaPostBattle: @ 829F138
	.string "I'm going to a Contest in Lilycove.\p"
	.string "My Pokémon should have no problem\n"
	.string "sweeping the Master Class.$"

Route121_Text_WalterIntro: @ 829F199
	.string "With my Pokémon, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterDefeat: @ 829F20D
	.string "Ah, well played.$"

Route121_Text_WalterPostBattle: @ 829F21E
	.string "I would like to circle the globe once\n"
	.string "again with my Pokémon.$"

Route121_Text_WalterRegister: @ 829F25B
	.string "Your Pokémon prowess is remarkable.\n"
	.string "Allow me to register you as a memento.$"

Route121_Text_WalterRematchIntro: @ 829F2A6
	.string "With my Pokémon, I have traveled\n"
	.string "to the world's four corners.\p"
	.string "You might say I have some confidence\n"
	.string "in my abilities.$"

Route121_Text_WalterRematchDefeat: @ 829F31A
	.string "Ah, well played.$"

Route121_Text_WalterPostRematch: @ 829F32B
	.string "Your Pokémon and you…\p"
	.string "Your prowess together will be\n"
	.string "considered strong, even overseas.$"

Route121_Text_TammyIntro: @ 829F381
	.string "There are powers beyond our\n"
	.string "understanding in the world…$"

Route121_Text_TammyDefeat: @ 829F3B9
	.string "I have lost…$"

Route121_Text_TammyPostBattle: @ 829F3C6
	.string "Mt. Pyre…\n"
	.string "There is a mysterious power\l"
	.string "at work there…$"

Route121_Text_KateIntro: @ 829F3FB
	.string "Kate: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_KateDefeat: @ 829F43F
	.string "Kate: I blew it in front of my junior\n"
	.string "student partner…$"

Route121_Text_KatePostBattle: @ 829F476
	.string "Kate: When someone's relying on me,\n"
	.string "I get this urge to look cool in front\l"
	.string "of them…$"

Route121_Text_KateNotEnoughMons: @ 829F4C9
	.string "Kate: If you've only got one Pokémon,\n"
	.string "we can't battle with you.\p"
	.string "That would be bullying.$"

Route121_Text_JoyIntro: @ 829F521
	.string "Joy: Together, we're fearless!\n"
	.string "We'll demonstrate how tough we are!$"

Route121_Text_JoyDefeat: @ 829F564
	.string "Joy: Please forgive me, Kate!$"

Route121_Text_JoyPostBattle: @ 829F582
	.string "Joy: Ehehe, I'll have to train with Kate,\n"
	.string "my senior student partner, again.$"

Route121_Text_JoyNotEnoughMons: @ 829F5CE
	.string "Joy: You need at least two Pokémon\n"
	.string "if you're going to challenge us!$"

Route121_Text_JessicaIntro: @ 829F612
	.string "Stop! Have a good look at my precious\n"
	.string "Pokémon!$"

Route121_Text_JessicaDefeat: @ 829F641
	.string "Oh, how dare you!\n"
	.string "Don't take it so seriously!$"

Route121_Text_JessicaPostBattle: @ 829F66F
	.string "Maybe I'll go catch more Pokémon at\n"
	.string "the Safari.$"

Route121_Text_JessicaRegister: @ 829F69F
	.string "I took it easy on you this time!\n"
	.string "It won't be that way the next time!$"

Route121_Text_JessicaRematchIntro: @ 829F6E4
	.string "My precious Pokémon grew!\n"
	.string "Have a good look!$"

Route121_Text_JessicaRematchDefeat: @ 829F710
	.string "Oh, how dare you!\n"
	.string "You still won't take it easy!$"

Route121_Text_JessicaPostRematch: @ 829F740
	.string "Maybe I'll go catch more Pokémon at\n"
	.string "the Safari.$"

Route121_Text_CristinIntro: @ 829F770
	.string "I have this routine.\n"
	.string "Defeat five Trainers a day.\l"
	.string "Guess what? You're number five!$"

Route121_Text_CristinDefeat: @ 829F7C1
	.string "No!\n"
	.string "You're horrid!$"

Route121_Text_CristinPostBattle: @ 829F7D4
	.string "I didn't expect to lose this easily…\n"
	.string "I'll win next time!$"

Route121_Text_CristinRegister: @ 829F80D
	.string "That was total humiliation!\n"
	.string "I won't forget you…\l"
	.string "Hand over your PokéNav!$"

Route121_Text_CristinRematchIntro: @ 829F855
	.string "I have this new routine.\n"
	.string "Defeat ten Trainers a day.\l"
	.string "Guess what? You're number ten!$"

Route121_Text_CristinRematchDefeat: @ 829F8A8
	.string "Wait! That's nasty!\n"
	.string "I demand a rematch!$"

Route121_Text_CristinPostRematch: @ 829F8D0
	.string "An opponent I just can't beat…\n"
	.string "Snivel…\l"
	.string "I can't believe this is happening…$"

Route121_Text_CaleIntro: @ 829F91A
	.string "Can't you see that I have all this\n"
	.string "stuff with me?\p"
	.string "Despite that, you still insist that\n"
	.string "we battle?$"

Route121_Text_CaleDefeat: @ 829F97B
	.string "Of course I lost!\n"
	.string "I'm holding stuff in both hands!$"

Route121_Text_CalePostBattle: @ 829F9AE
	.string "I bought too much stuff at\n"
	.string "the Lilycove Dept. Store.\p"
	.string "It's up the road from here.\n"
	.string "I wish I had a Bag like yours.$"

Route121_Text_MylesIntro: @ 829FA1E
	.string "There's nothing I love more than\n"
	.string "checking out other people's Pokémon!$"

Route121_Text_MylesDefeat: @ 829FA64
	.string "Super awesome!$"

Route121_Text_MylesPostBattle: @ 829FA73
	.string "They're great, your Pokémon!\n"
	.string "How do you raise them?$"

Route121_Text_PatIntro: @ 829FAA7
	.string "I want everybody to see the Pokémon\n"
	.string "I've raised!$"

Route121_Text_PatDefeat: @ 829FAD8
	.string "Wow!\n"
	.string "Spectacular!$"

Route121_Text_PatPostBattle: @ 829FAEA
	.string "I raise every Pokémon with the same\n"
	.string "love and care--I don't pick favorites.$"

Route121_Text_MarcelIntro: @ 829FB35
	.string "My Pokémon have never tasted defeat!\n"
	.string "On their next win, I'm entering them\l"
	.string "in Contests.$"

Route121_Text_MarcelDefeat: @ 829FB8C
	.string "Oh, now what happened here?$"

Route121_Text_MarcelPostBattle: @ 829FBA8
	.string "I may have to train my gang some more\n"
	.string "before entering any Contest.$"

Route123_Text_WendyIntro: @ 829FBEB
	.string "Want to determine how strong you are?\n"
	.string "I'll be the test!$"

Route123_Text_WendyDefeat: @ 829FC23
	.string "You passed with flying colors!$"

Route123_Text_WendyPostBattle: @ 829FC42
	.string "To best even me…\n"
	.string "Your strength is marvelous!$"

Route123_Text_BraxtonIntro: @ 829FC6F
	.string "You seem to have a big collection\n"
	.string "of Gym Badges.\p"
	.string "Let me see if you're actually worthy of\n"
	.string "those Badges!$"

Route123_Text_BraxtonDefeat: @ 829FCD6
	.string "Oh, you're worthy, all right!$"

Route123_Text_BraxtonPostBattle: @ 829FCF4
	.string "You did your Badges proud in that\n"
	.string "match!$"

Route123_Text_VioletIntro: @ 829FD1D
	.string "I only recently found out that you can\n"
	.string "drag cards into the Retreat Area…$"

Route123_Text_VioletDefeat: @ 829FD53
	.string "I've been right click to move to Retreat\n"
	.string "for like a year now…$"

Route123_Text_VioletPostBattle: @ 829FD7B
	.string "I've been right click to move to Retreat\n"
	.string "for like a year now…$"

Route123_Text_CameronIntro: @ 829FDBA
	.string "Being a psychic is about willpower.\p"
	.string "I've willed myself not to lose to\n"
	.string "anyone. That makes me strong!$"

Route123_Text_CameronDefeat: @ 829FE1E
	.string "I feel sad…$"

Route123_Text_CameronPostBattle: @ 829FE2A
	.string "Being a psychic is about willpower.\n"
	.string "I thought I wouldn't lose to you…$"

Route123_Text_CameronRegister: @ 829FE70
	.string "I sense it!\n"
	.string "You and I shall battle again!\l"
	.string "I can't tell if I'll win, though…\p"
	.string "Let's see your PokéNav.$"

Route123_Text_CameronRematchIntro: @ 829FED4
	.string "I've convinced myself that I won't\n"
	.string "lose anymore. That makes me strong!$"

Route123_Text_CameronRematchDefeat: @ 829FF1B
	.string "I feel sad…$"

Route123_Text_CameronPostRematch: @ 829FF27
	.string "I should train at Mt. Pyre…\n"
	.string "I'll never beat you this way…$"

Route123_Text_JackiIntro: @ 829FF61
	.string "Don't be too happy if your Pokémon\n"
	.string "develop psychic powers.\p"
	.string "You need to refine those powers to\n"
	.string "make them really useful.$"

Route123_Text_JackiDefeat: @ 829FFD8
	.string "Overwhelmed!$"

Route123_Text_JackiPostBattle: @ 829FFE5
	.string "We all have psychic powers.\n"
	.string "We've just forgotten how to use them.$"

Route123_Text_JackiRegister: @ 82A0027
	.string "I would like to face you again.\n"
	.string "Is that okay with you?$"

Route123_Text_JackiRematchIntro: @ 82A005E
	.string "Have you awoken the psychic powers\n"
	.string "within you?$"

Route123_Text_JackiRematchDefeat: @ 82A008D
	.string "Astounding!$"

Route123_Text_JackiPostRematch: @ 82A0099
	.string "Your power with Pokémon…\n"
	.string "That could be a psychic power, too.$"

Route123_Text_MiuIntro: @ 82A00D6
	.string "I've moved from pinging Lackey Duelist\n"
	.string "every day to pinging Hunters every day.$"

Route123_Text_MiuDefeat: @ 82A0119
	.string "This is a best of 1 too?$"

Route123_Text_MiuPostBattle: @ 82A012E
	.string "This is a best of 1 too?$"

Route123_Text_MiuNotEnoughMons: @ 82A016D
	.string "Miu: It's no fun to battle if you\n"
	.string "don't have two Pokémon.$"

Route123_Text_YukiIntro: @ 82A01A7
	.string "Yuki: Okay!\n"
	.string "We're beating the Trainer's Pokémon!$"

Route123_Text_YukiDefeat: @ 82A01D8
	.string "Yuki: Uh-oh, we lost.$"

Route123_Text_YukiPostBattle: @ 82A01EE
	.string "Yuki: Why are you so strong?\n"
	.string "We've never lost before.$"

Route123_Text_YukiNotEnoughMons: @ 82A0224
	.string "Yuki: It's no fun to battle if you\n"
	.string "don't have two Pokémon.$"

Route123_Text_KindraIntro: @ 82A025F
	.string "Mt. Pyre…\n"
	.string "Where the spirits of Pokémon sleep…\l"
	.string "Will your Pokémon sleep?$"

Route123_Text_KindraDefeat: @ 82A02A6
	.string "Overflowing with vitality…$"

Route123_Text_KindraPostBattle: @ 82A02C1
	.string "Mt. Pyre…\n"
	.string "Where the spirits of Pokémon sleep…\p"
	.string "It must overflow with a power that\n"
	.string "soothes spirits…$"

Route123_Text_FernandoIntro: @ 82A0323
	.string "I'll turn your lights out while\n"
	.string "I rip through this tune!$"

Route123_Text_FernandoDefeat: @ 82A035C
	.string "Hey, hold it!\n"
	.string "I was still playing the intro!$"

Route123_Text_FernandoPostBattle: @ 82A0389
	.string "You're rock steady.\n"
	.string "I'd like to write a tune about you.$"

Route123_Text_FernandoRegister: @ 82A03C1
	.string "The next time, lend your ears to\n"
	.string "the full tune, will you?$"

Route123_Text_FernandoRematchIntro: @ 82A03FB
	.string "Today's the day I'm going to do it!\n"
	.string "I'll turn out your lights before\l"
	.string "I finish singing my song!$"

Route123_Text_FernandoRematchDefeat: @ 82A045A
	.string "Hey, hold it!\n"
	.string "I haven't even hit the chorus!$"

Route123_Text_FernandoPostRematch: @ 82A0487
	.string "I thought you'd be so enthralled\n"
	.string "by my tune, you'd lose.$"

Route123_Text_DavisIntro: @ 82A04C0
	.string "Radiant Dawn is a terrible game-\n"
	.string "having basically 4 armies sucks,\p"
	.string "the Dawn Brigade sucks, and at the\n"
	.string "end of the game the Laguz Royals\l"
	.string "are dumped on you to replace everything.$"

Route123_Text_DavisDefeat: @ 82A04FE
	.string "PoR is peak though.$"

Route123_Text_DavisPostBattle: @ 82A0512
	.string "PoR is peak though.$"

Route123_Text_JazmynIntro: @ 82A054E
	.string "I've only got 763 more Cipher cards\n"
	.string "to collect. $"

Route123_Text_JazmynDefeat: @ 82A0592
	.string "Welp, gonna need more time for my\n"
	.string "coffers to recharge…$"

Route123_Text_JazmynPostBattle: @ 82A05AC
	.string "Welp, gonna need more time for my\n"
	.string "coffers to recharge…$"

Route123_Text_FrederickIntro: @ 82A060A
	.string "Hello, child!\n"
	.string "Can you spare some time?$"

Route123_Text_FrederickDefeat: @ 82A0631
	.string "Ah, a mighty capable child!\n"
	.string "Let me contribute to your allowance.$"

Route123_Text_FrederickPostBattle: @ 82A0672
	.string "Contribute to your allowance?\n"
	.string "Wasn't the prize money enough?$"

Route123_Text_AlbertoIntro: @ 82A06AF
	.string "I have to tell you, Bird Pokémon\n"
	.string "are my obsession!\p"
	.string "Birds are cool!\n"
	.string "They're the best!$"

Route123_Text_AlbertoDefeat: @ 82A0704
	.string "Even in defeat, Bird Pokémon are cool!$"

Route123_Text_AlbertoPostBattle: @ 82A072B
	.string "I gather Bird Pokémon feathers that\n"
	.string "scatter during battles.\p"
	.string "I'm going to make a hat with\n"
	.string "Bird Pokémon feathers.$"

Route123_Text_EdIntro: @ 82A079B
	.string "When there are no Trainers around,\n"
	.string "I let my Pokémon battle each other.\l"
	.string "I watch them.$"

Route123_Text_EdDefeat: @ 82A07F0
	.string "I kind of like your Pokémon.$"

Route123_Text_EdPostBattle: @ 82A080D
	.string "Hehe, I'm swiping your battling ideas!\n"
	.string "I think they'll make me better.$"

Route123_Text_JonasIntro: @ 82A0854
	.string "I lay in ambush, and a Trainer has\n"
	.string "landed in my trap!$"

Route123_Text_JonasDefeat: @ 82A088A
	.string "If you don't lose, how am I supposed\n"
	.string "to have fun playing ninja?$"

Route123_Text_JonasPostBattle: @ 82A08CA
	.string "I'm going to ambush a weaker-looking\n"
	.string "Trainer next time.$"

Route123_Text_KayleyIntro: @ 82A0902
	.string "I just bought this parasol.\n"
	.string "My cuteness should be up by a third!$"

Route123_Text_KayleyDefeat: @ 82A0943
	.string "You're better than me by about\n"
	.string "five times!$"

Route123_Text_KayleyPostBattle: @ 82A096E
	.string "Using accessories effectively is\n"
	.string "the secret behind fashion appeal.$"

Route124_Text_SpencerIntro: @ 82A09B1
	.string "Hey, are you lost at sea?\p"
	.string "If you can beat my Pokémon,\n"
	.string "I can serve as your pilot.$"

Route124_Text_SpencerDefeat: @ 82A0A02
	.string "I lost my bearings in battle!$"

Route124_Text_SpencerPostBattle: @ 82A0A20
	.string "Many people lose their bearings at sea.\p"
	.string "If you're that sort, you should refer\n"
	.string "to the PokéNav's Map.$"

Route124_Text_RolandIntro: @ 82A0A84
	.string "Hm! You're riding a Pokémon instead\n"
	.string "of swimming yourself…\p"
	.string "I am envious!$"

Route124_Text_RolandDefeat: @ 82A0ACC
	.string "Oh!\n"
	.string "I can't…$"

Route124_Text_RolandPostBattle: @ 82A0AD9
	.string "I'm getting chilled…\n"
	.string "I've been in the water too long…\p"
	.string "I wish I could ride a Pokémon like you…$"

Route124_Text_JennyIntro: @ 82A0B37
	.string "If you just float in the sea like\n"
	.string "this, Pokémon come around to play.$"

Route124_Text_JennyDefeat: @ 82A0B7C
	.string "Oh, darn.\n"
	.string "I've gone and lost.$"

Route124_Text_JennyPostBattle: @ 82A0B9A
	.string "While swimming, I noticed that some\n"
	.string "Pokémon attack, and some just watch.\p"
	.string "I guess Pokémon have personalities\n"
	.string "of their own.$"

Route124_Text_JennyRegister: @ 82A0C14
	.string "It's only on a whim, but maybe I'll get\n"
	.string "you to register me in your PokéNav.$"

Route124_Text_JennyRematchIntro: @ 82A0C60
	.string "If you just float in the sea like this,\n"
	.string "Trainers challenge you!$"

Route124_Text_JennyRematchDefeat: @ 82A0CA0
	.string "That's strange…\n"
	.string "I lost again…$"

Route124_Text_JennyPostRematch: @ 82A0CBE
	.string "This has nothing to do with anything,\n"
	.string "but maybe I'll visit the Trick House.$"

Route124_Text_GraceIntro: @ 82A0D0A
	.string "I'm growing bored of swimming…\n"
	.string "How about a battle?$"

Route124_Text_GraceDefeat: @ 82A0D3D
	.string "I had no idea that you were\n"
	.string "this strong!$"

Route124_Text_GracePostBattle: @ 82A0D66
	.string "All the effort you put in must have\n"
	.string "made you this strong.$"

Route124_Text_ChadIntro: @ 82A0DA0
	.string "Fufufufu… I dive deep underwater\n"
	.string "to go deep under cover.\l"
	.string "Plumbing the depths is where I excel!$"

Route124_Text_ChadDefeat: @ 82A0DFF
	.string "Glub, glub, glub…\n"
	.string "I'm sinking…$"

Route124_Text_ChadPostBattle: @ 82A0E1E
	.string "I have it on good authority that\n"
	.string "there's a Dive spot around here.\p"
	.string "It gives me the urge to go deep\n"
	.string "again…$"

Route124_Text_LilaIntro: @ 82A0E87
	.string "Lila: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Let's battle so I won't have to dwell\n"
	.string "on that!$"

Route124_Text_LilaDefeat: @ 82A0EFE
	.string "Lila: Roy! It's your fault we lost!\n"
	.string "You're in for it later!$"

Route124_Text_LilaPostBattle: @ 82A0F3A
	.string "Lila: Sigh…\p"
	.string "If only it wasn't my little brother\n"
	.string "next to me, but a nice boyfriend…$"

Route124_Text_LilaNotEnoughMons: @ 82A0F8C
	.string "Lila: You're planning to battle us?\n"
	.string "Not unless you have two Pokémon.$"

Route124_Text_RoyIntro: @ 82A0FD1
	.string "Roy: My big sister is tough at Pokémon!\p"
	.string "Don't cry when you lose!$"

Route124_Text_RoyDefeat: @ 82A1012
	.string "Roy: Uh-oh…\n"
	.string "My big sister will chew me out…$"

Route124_Text_RoyPostBattle: @ 82A103E
	.string "Roy: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "That's why she doesn't have a\n"
	.string "boyfriend.$"

Route124_Text_LilaRoyRegister: @ 82A109F
	.string "Roy: Will you battle with us again?\n"
	.string "But take it easy next time, okay?$"

Route124_Text_RoyNotEnoughMons: @ 82A10E5
	.string "Roy: Did you want to battle us?\n"
	.string "Bring two Pokémon, then.$"

Route124_Text_LilaRematchIntro: @ 82A111E
	.string "Lila: Sigh…\p"
	.string "Here I am in the sea, but who's with me?\n"
	.string "My little brother!\p"
	.string "Oh, hi, it's been a while. Let's battle\n"
	.string "so I won't have to dwell on things!$"

Route124_Text_LilaRematchDefeat: @ 82A11B2
	.string "Lila: Roy!\n"
	.string "It's your fault we lost again!\p"
	.string "We're having a training session later!$"

Route124_Text_LilaPostRematch: @ 82A1203
	.string "Lila: Sigh…\p"
	.string "If I had a nice boyfriend, we'd beat\n"
	.string "anyone with lovely combinations…$"

Route124_Text_LilaRematchNotEnoughMons: @ 82A1255
	.string "Lila: You're planning to battle us?\n"
	.string "Not unless you have two Pokémon.$"

Route124_Text_RoyRematchIntro: @ 82A129A
	.string "Roy: If we lose, I'll catch heck.\n"
	.string "I'm going to go totally all out!$"

Route124_Text_RoyRematchDefeat: @ 82A12DD
	.string "Roy: Uh-oh…\n"
	.string "My big sister will chew me out again.$"

Route124_Text_RoyPostRematch: @ 82A130F
	.string "Roy: My big sister is really scary\n"
	.string "when she gets angry.\p"
	.string "She's going to make me train really\n"
	.string "hard with Pokémon later…$"

Route124_Text_RoyRematchNotEnoughMons: @ 82A1384
	.string "Roy: Did you want to battle us?\n"
	.string "Bring two Pokémon, then.$"

Route124_Text_DeclanIntro: @ 82A13BD
	.string "Here I am swimming by my lonesome\n"
	.string "on this wide, beautiful sea.\p"
	.string "There's no other word for it.\n"
	.string "This is pathetic!$"

Route124_Text_DeclanDefeat: @ 82A142C
	.string "I'm feeling blue.\n"
	.string "Blue as the sky…$"

Route124_Text_DeclanPostBattle: @ 82A144F
	.string "I should chat up lady Swimmers\n"
	.string "and invite them on a long swim.$"

Route124_Text_IsabellaIntro: @ 82A148E
	.string "I'm not going to lose to some\n"
	.string "surfer Trainer.$"

Route124_Text_IsabellaDefeat: @ 82A14BC
	.string "I've only got sweat in my eyes!\n"
	.string "I am not crying!$"

Route124_Text_IsabellaPostBattle: @ 82A14ED
	.string "You can find pretty colored shards\n"
	.string "of things around here.$"

Route125_Text_NolenIntro: @ 82A1527
	.string "I heard you approaching, so I hung\n"
	.string "around for you!$"

Route125_Text_NolenDefeat: @ 82A155A
	.string "I surrender!$"

Route125_Text_NolenPostBattle: @ 82A1567
	.string "Sound travels faster in water than\n"
	.string "it does through air.$"

Route125_Text_StanIntro: @ 82A159F
	.string "Hey, there!\n"
	.string "Check out my sweet Pokémon!$"

Route125_Text_StanDefeat: @ 82A15C7
	.string "I floundered…$"

Route125_Text_StanPostBattle: @ 82A15D5
	.string "I was blown away by HORSEA's charm,\n"
	.string "so I started swimming, too.$"

Route125_Text_TanyaIntro: @ 82A1615
	.string "I'm tired of swimming.\n"
	.string "Are you up for a battle with me?$"

Route125_Text_TanyaDefeat: @ 82A164D
	.string "You're too much!$"

Route125_Text_TanyaPostBattle: @ 82A165E
	.string "Whew…\n"
	.string "Which way is it to Mossdeep City?$"

Route125_Text_SharonIntro: @ 82A1686
	.string "How would you like to take on the\n"
	.string "Water-type Pokémon I raised?$"

Route125_Text_SharonDefeat: @ 82A16C5
	.string "Lost it…$"

Route125_Text_SharonPostBattle: @ 82A16CE
	.string "Your power… You're the real deal.\n"
	.string "I'm amazed!$"

Route125_Text_ErnestIntro: @ 82A16FC
	.string "Ahoy! I'm a buff, tough Sailor!\n"
	.string "I've braved the world's seas!$"

Route125_Text_ErnestDefeat: @ 82A173A
	.string "Gwrroooar!\n"
	.string "I couldn't win!$"

Route125_Text_ErnestPostBattle: @ 82A1755
	.string "The tide ebbs and flows inside the\n"
	.string "Shoal Cave.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Did you know?$"

Route125_Text_ErnestRegister: @ 82A17CF
	.string "Register me in your PokéNav,\n"
	.string "and I'll tell you something good.$"

Route125_Text_ErnestRematchIntro: @ 82A180E
	.string "It's high time I get my payback\n"
	.string "from you! Come on, we're battling!$"

Route125_Text_ErnestRematchDefeat: @ 82A1851
	.string "I couldn't win!\n"
	.string "I flat out couldn't win!$"

Route125_Text_ErnestRematchPostBattle: @ 82A187A
	.string "The Shoal Cave…\p"
	.string "There are places you can and can't\n"
	.string "get to depending on the rise and fall\l"
	.string "of the tide.\p"
	.string "By the way, it's about six hours from\n"
	.string "high tide to low tide. Don't forget!$"

Route125_Text_KimIntro: @ 82A192B
	.string "Kim: A funny old man lives in the\n"
	.string "Shoal Cave. Someone told me.\l"
	.string "Are you going to see him, too?$"

Route125_Text_KimDefeat: @ 82A1989
	.string "Kim: I thought we would win.$"

Route125_Text_KimPostBattle: @ 82A19A6
	.string "Kim: A funny old man lives in the\n"
	.string "Shoal Cave, doesn't he?\p"
	.string "Let's go see him, Iris!$"

Route125_Text_KimNotEnoughMons: @ 82A19F8
	.string "Kim: No, no, no! You need two Pokémon,\n"
	.string "or it's just no good!$"

Route125_Text_IrisIntro: @ 82A1A35
	.string "Iris: Kim, can you tell me what we're\n"
	.string "looking for out here?$"

Route125_Text_IrisDefeat: @ 82A1A71
	.string "Iris: Oh, we came sort of close.$"

Route125_Text_IrisPostBattle: @ 82A1A92
	.string "Iris: Kim, are we really going into\n"
	.string "the Shoal Cave?\l"
	.string "We'll get all wet.$"

Route125_Text_IrisNotEnoughMons: @ 82A1AD9
	.string "Iris: Oh, we could never, ever do\n"
	.string "anything like a 2-on-1 battle.$"

Route125_Text_PresleyIntro: @ 82A1B1A
	.string "Why would a Birdkeeper like me\n"
	.string "come out to the sea?$"

Route125_Text_PresleyDefeat: @ 82A1B4E
	.string "Okay.\n"
	.string "I'll tell you why I'm here.$"

Route125_Text_PresleyPostBattle: @ 82A1B70
	.string "I put a message in a bottle and put\n"
	.string "it out to sea.\p"
	.string "I'm sure that a girl Swimmer will\n"
	.string "find it!$"

Route125_Text_AuronIntro: @ 82A1BCE
	.string "Hey! Was it you throwing garbage\n"
	.string "into the sea?$"

Route125_Text_AuronDefeat: @ 82A1BFD
	.string "Oh, you weren't throwing trash into\n"
	.string "the sea.$"

Route125_Text_AuronPostBattle: @ 82A1C2A
	.string "I found an unsightly bottle bobbing\n"
	.string "in the waves earlier.\p"
	.string "It angers me that someone would\n"
	.string "pollute the sea!$"

Route126_Text_BarryIntro: @ 82A1C95
	.string "Swimming is a full-body workout!\n"
	.string "You will get fit!$"

Route126_Text_BarryDefeat: @ 82A1CC8
	.string "I admit it!\n"
	.string "You win!$"

Route126_Text_BarryPostBattle: @ 82A1CDD
	.string "Thanks to my daily swimming routine…\n"
	.string "Look! Feast your eyes on this physique!$"

Route126_Text_DeanIntro: @ 82A1D2A
	.string "This towering white mountain of rock\n"
	.string "is Sootopolis City.$"

Route126_Text_DeanDefeat: @ 82A1D63
	.string "I was done in?$"

Route126_Text_DeanPostBattle: @ 82A1D72
	.string "I can't find the entrance to\n"
	.string "Sootopolis. Where could it be?$"

Route126_Text_NikkiIntro: @ 82A1DAE
	.string "Ufufufufu!\n"
	.string "I'm a mermaid!$"

Route126_Text_NikkiDefeat: @ 82A1DC8
	.string "My fantasy burst as if it were a bubble!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiPostBattle: @ 82A1E03
	.string "You thrashed me… I want to\n"
	.string "disappear in a wave of despair…$"

Route126_Text_BrendaIntro: @ 82A1E3E
	.string "Hello, kiddo!\n"
	.string "Want a battle with me?$"

Route126_Text_BrendaDefeat: @ 82A1E63
	.string "Oh, noooooh!$"

Route126_Text_BrendaPostBattle: @ 82A1E70
	.string "I love frolicking with Pokémon in\n"
	.string "the sea like this!$"

Route126_Text_PabloIntro: @ 82A1EA5
	.string "Check out this sculpted body!\n"
	.string "I'm more cut than a Black Belt!$"

Route126_Text_PabloDefeat: @ 82A1EE3
	.string "Whoops! Too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostBattle: @ 82A1F10
	.string "Losing to you stimulated my senses!\n"
	.string "I'll train myself and Pokémon harder!$"

Route126_Text_PabloRegister: @ 82A1F5A
	.string "Yep, you're not bad at all!\n"
	.string "I'd like to get to know you more!$"

Route126_Text_PabloRematchIntro: @ 82A1F98
	.string "Check out this beautiful body!\n"
	.string "I'm more shapely than a Swimmer!$"

Route126_Text_PabloRematchDefeat: @ 82A1FD8
	.string "Whoops! Really too strong!\n"
	.string "Not bad! Not bad at all!$"

Route126_Text_PabloPostRematch: @ 82A200C
	.string "I'm going to train even harder!\n"
	.string "You're a great motivator!\l"
	.string "You have to come back again!$"

Route126_Text_LeonardoIntro: @ 82A2063
	.string "I couldn't even swim last year,\n"
	.string "but now I'm a decent Swimmer.\p"
	.string "I think I'm capable of anything now.$"

Route126_Text_LeonardoDefeat: @ 82A20C6
	.string "Sheesh, getting greedy didn't do\n"
	.string "a thing for me.$"

Route126_Text_LeonardoPostBattle: @ 82A20F7
	.string "If you practice at something,\n"
	.string "you will get better at it.\p"
	.string "You're young--don't be afraid to\n"
	.string "try all sorts of things!$"

Route126_Text_IsobelIntro: @ 82A216A
	.string "If seawater gets up your nose,\n"
	.string "doesn't it feel terrible?$"

Route126_Text_IsobelDefeat: @ 82A21A3
	.string "Ack! Why, you…\n"
	.string "Glub!$"

Route126_Text_IsobelPostBattle: @ 82A21B8
	.string "Ooh, I choked on some water!\n"
	.string "It's bitter! It's salty!!$"

Route126_Text_SiennaIntro: @ 82A21EF
	.string "I'm throwing my whole heart\n"
	.string "into this!$"

Route126_Text_SiennaDefeat: @ 82A2216
	.string "You had more heart!$"

Route126_Text_SiennaPostBattle: @ 82A222A
	.string "I need to cool down now…\n"
	.string "I think I'll go for a dive.$"

Route127_Text_CamdenIntro: @ 82A225F
	.string "I can see it in your face.\n"
	.string "You want to challenge me.$"

Route127_Text_CamdenDefeat: @ 82A2294
	.string "Awawawawawa…$"

Route127_Text_CamdenPostBattle: @ 82A22A1
	.string "A well-played match leaves me feeling\n"
	.string "refreshed and serene.$"

Route127_Text_DonnyIntro: @ 82A22DD
	.string "Do you have a rival whom you just\n"
	.string "hate to lose against?$"

Route127_Text_DonnyDefeat: @ 82A2315
	.string "Arrrgh!\n"
	.string "I hate losing!$"

Route127_Text_DonnyPostBattle: @ 82A232C
	.string "If you have a rival, don't you get the\n"
	.string "feeling that you have to keep getting\l"
	.string "better?$"

Route127_Text_JonahIntro: @ 82A2381
	.string "Through fishing, I have attained a\n"
	.string "state of becalmed serenity…\p"
	.string "Please, allow me to demonstrate…$"

Route127_Text_JonahDefeat: @ 82A23E1
	.string "Though I have lost, my heart remains\n"
	.string "calm…$"

Route127_Text_JonahPostBattle: @ 82A240C
	.string "It matters not that I catch nothing.\n"
	.string "The line remains in the water…$"

Route127_Text_HenryIntro: @ 82A2450
	.string "Whoops! Don't tell me I snagged\n"
	.string "a Surfing Pokémon?$"

Route127_Text_HenryDefeat: @ 82A2483
	.string "I can't keep up!$"

Route127_Text_HenryPostBattle: @ 82A2494
	.string "It'd be a handful if I hooked\n"
	.string "your tough Pokémon!$"

Route127_Text_RogerIntro: @ 82A24C6
	.string "Well, hey! This is a match between\n"
	.string "a Pokémon fan and a fishing buff!$"

Route127_Text_RogerDefeat: @ 82A250B
	.string "No! My line's all tangled!\n"
	.string "The party's over!$"

Route127_Text_RogerPostBattle: @ 82A2538
	.string "My fishing line's doing a dance!\n"
	.string "The tangle tango! Hahaha, snarl!$"

Route127_Text_AidanIntro: @ 82A257A
	.string "Bird Pokémon have excellent vision.\n"
	.string "They spot prey from great heights.$"

Route127_Text_AidanDefeat: @ 82A25C1
	.string "Whew… I give up.$"

Route127_Text_AidanPostBattle: @ 82A25D2
	.string "There're lots of diving spots in\n"
	.string "the sea around here.\p"
	.string "You can spot them easily from the sky\n"
	.string "because of their darker color.$"

Route127_Text_KojiIntro: @ 82A264D
	.string "Run in your bare feet.\n"
	.string "That will toughen up your soles!$"

Route127_Text_KojiDefeat: @ 82A2685
	.string "Yowch!\n"
	.string "I got a pebble under a toenail!$"

Route127_Text_KojiPostBattle: @ 82A26AC
	.string "Going barefoot feels great.\n"
	.string "But your Running Shoes are cool, too.$"

Route127_Text_KojiRegister: @ 82A26EE
	.string "This is what I do to people who beat me!\n"
	.string "I hope we can do this again.$"

Route127_Text_KojiRematchIntro: @ 82A2734
	.string "I still run in my bare feet daily.\n"
	.string "My soles are tough!$"

Route127_Text_KojiRematchDefeat: @ 82A276B
	.string "Yowch!\n"
	.string "Pebbles dug into my arches!$"

Route127_Text_KojiPostRematch: @ 82A278E
	.string "Want to go barefoot for a while?\n"
	.string "So I can try your Running Shoes?$"

Route127_Text_AthenaIntro: @ 82A27D0
	.string "We should have a slow and methodical\n"
	.string "match.$"

Route127_Text_AthenaDefeat: @ 82A27FC
	.string "You didn't give me the chance to\n"
	.string "do any strategizing.$"

Route127_Text_AthenaPostBattle: @ 82A2832
	.string "When I'm surrounded by the blue sea\n"
	.string "and sky, it feels as if time slows down.$"

Route128_Text_IsaiahIntro: @ 82A287F
	.string "Ever Grande City is still a long ways\n"
	.string "away…$"

Route128_Text_IsaiahDefeat: @ 82A28AB
	.string "My first victory seems to be far\n"
	.string "away, too…$"

Route128_Text_IsaiahPostBattle: @ 82A28D7
	.string "My whole life has been about losing,\n"
	.string "but I will never give up!$"

Route128_Text_IsaiahRegister: @ 82A2916
	.string "I know I'm not good now, but I think\n"
	.string "I can win eventually.\p"
	.string "Please register me in your PokéNav.$"

Route128_Text_IsaiahRematchIntro: @ 82A2975
	.string "I'm still feeling good. I'll keep on\n"
	.string "swimming to Ever Grande City.$"

Route128_Text_IsaiahRematchDefeat: @ 82A29B8
	.string "I've yet to taste my first victory…$"

Route128_Text_IsaiahPostRematch: @ 82A29DC
	.string "I'll eventually reach Ever Grande City\n"
	.string "where I can eventually win…$"

Route128_Text_KatelynIntro: @ 82A2A1F
	.string "You have to swim, cycle, and then run\n"
	.string "a marathon in a triathlon.\p"
	.string "It's a grueling race that consists\n"
	.string "of three events.$"

Route128_Text_KatelynDefeat: @ 82A2A94
	.string "A Pokémon battle is grueling, too…$"

Route128_Text_KatelynPostBattle: @ 82A2AB7
	.string "I have to ride a Bike next, but…\n"
	.string "I'm about to throw in the towel…$"

Route128_Text_KatelynRegister: @ 82A2AF9
	.string "Well, I may as well make the best\n"
	.string "of this. I'd like a rematch sometime.$"

Route128_Text_KatelynRematchIntro: @ 82A2B41
	.string "A triathlon is long. But I guess the\n"
	.string "road to become the Pokémon Champion\l"
	.string "is also a long and grueling one.$"

Route128_Text_KatelynRematchDefeat: @ 82A2BAB
	.string "A Pokémon battle really is harsh\n"
	.string "and unforgiving…$"

Route128_Text_KatelynPostRematch: @ 82A2BDD
	.string "You should give serious thought to\n"
	.string "challenges on Victory Road.$"

Route128_Text_AlexaIntro: @ 82A2C1C
	.string "We've been working so hard to mount\n"
	.string "a Pokémon League challenge…\p"
	.string "We can't afford to lose now!$"

Route128_Text_AlexaDefeat: @ 82A2C79
	.string "Oh!\n"
	.string "How could this happen?!$"

Route128_Text_AlexaPostBattle: @ 82A2C95
	.string "After all I've done to get here,\n"
	.string "I won't give up after one setback.$"

Route128_Text_RubenIntro: @ 82A2CD9
	.string "There is no stronger Trainer than I!$"

Route128_Text_RubenDefeat: @ 82A2CFE
	.string "This can't be!$"

Route128_Text_RubenPostBattle: @ 82A2D0D
	.string "There probably is no stronger Trainer\n"
	.string "than you!$"

Route128_Text_WayneIntro: @ 82A2D3D
	.string "I want to visit Ever Grande, so I\n"
	.string "caught myself a Pokémon that knows\l"
	.string "the move Waterfall to crest the falls.$"

Route128_Text_WayneDefeat: @ 82A2DA9
	.string "I'm crestfallen!$"

Route128_Text_WaynePostBattle: @ 82A2DBA
	.string "Awww, phooey!\p"
	.string "My Pokémon knows Waterfall, but\n"
	.string "I don't have the Sootopolis Gym Badge!$"

Route128_Text_HarrisonIntro: @ 82A2E0F
	.string "You're looking awfully tough.\n"
	.string "I wonder if I can win?$"

Route128_Text_HarrisonDefeat: @ 82A2E44
	.string "Ouch!\n"
	.string "I guess it was impossible to win.$"

Route128_Text_HarrisonPostBattle: @ 82A2E6C
	.string "There are tough Trainers galore\n"
	.string "around Ever Grande.\p"
	.string "Do you think I may be out\n"
	.string "of my league?$"

Route128_Text_CarleeIntro: @ 82A2EC8
	.string "The sunlight seems to be more harsh\n"
	.string "in this area.$"

Route128_Text_CarleeDefeat: @ 82A2EFA
	.string "I couldn't see very well because of\n"
	.string "the sun's glare.$"

Route128_Text_CarleePostBattle: @ 82A2F2F
	.string "I should go back soon.\n"
	.string "I need to reapply my sunscreen.$"

Route129_Text_ChaseIntro: @ 82A2F66
	.string "This is my first triathlon.\n"
	.string "I'm all tense and nervous!$"

Route129_Text_ChaseDefeat: @ 82A2F9D
	.string "Wroooaaar!\n"
	.string "I failed to win!$"

Route129_Text_ChasePostBattle: @ 82A2FB9
	.string "If I'm all tensed up, I won't be able to\n"
	.string "give it my all.$"

Route129_Text_AllisonIntro: @ 82A2FF2
	.string "I'm in the middle of a triathlon,\n"
	.string "but, sure, why don't we battle?$"

Route129_Text_AllisonDefeat: @ 82A3034
	.string "I was sure I'd win!$"

Route129_Text_AllisonPostBattle: @ 82A3048
	.string "Do you know what's the greatest thing\n"
	.string "about triathlons?\p"
	.string "Testing the limits of your own\n"
	.string "strength and endurance against\l"
	.string "Mother Nature!$"

Route129_Text_ReedIntro: @ 82A30CD
	.string "Say hey, hey!\n"
	.string "Let's get on with it!$"

Route129_Text_ReedDefeat: @ 82A30F1
	.string "Beat, I'm beaten.\n"
	.string "That's it, done!$"

Route129_Text_ReedPostBattle: @ 82A3114
	.string "There's nothing for a loser.\n"
	.string "Time for me to beat it home.$"

Route129_Text_TishaIntro: @ 82A314E
	.string "What's the hurry?\n"
	.string "Let's take it slow and easy.$"

Route129_Text_TishaDefeat: @ 82A317D
	.string "Oh, my.\n"
	.string "I wanted to relax a little more…$"

Route129_Text_TishaPostBattle: @ 82A31A6
	.string "Don't you hate making mistakes when\n"
	.string "you're in a rush?\p"
	.string "That's why I try to take things\n"
	.string "slowly.$"

Route129_Text_ClarenceIntro: @ 82A3204
	.string "Surfing isn't as easy as it seems,\n"
	.string "isn't that right?$"

Route129_Text_ClarenceDefeat: @ 82A3239
	.string "Winning sure isn't easy.$"

Route129_Text_ClarencePostBattle: @ 82A3252
	.string "You have your sights on the Pokémon\n"
	.string "League? Keep at it!$"

Route130_Text_RodneyIntro: @ 82A328A
	.string "What a surprise! I didn't expect to\n"
	.string "see a Trainer out in the sea.\p"
	.string "I think we should battle!$"

Route130_Text_RodneyDefeat: @ 82A32E6
	.string "This kid's awfully tough…$"

Route130_Text_RodneyPostBattle: @ 82A3300
	.string "Your eyes have that look of someone\n"
	.string "who's experienced harsh challenges\l"
	.string "and won. It suits you well!$"

Route130_Text_KatieIntro: @ 82A3363
	.string "In the deep blue sea,\n"
	.string "my shattered blue heart finds\l"
	.string "comfort among waves.$"

Route130_Text_KatieDefeat: @ 82A33AC
	.string "Like the vast blue sea,\n"
	.string "the world of Pokémon spans\l"
	.string "depths beyond belief.$"

Route130_Text_KatiePostBattle: @ 82A33F5
	.string "The world's children dream\n"
	.string "of one day becoming\l"
	.string "the Pokémon Champion.$"

Route130_Text_SantiagoIntro: @ 82A343A
	.string "Floating on the open sea like this…\n"
	.string "It's peaceful.$"

Route130_Text_SantiagoDefeat: @ 82A346D
	.string "I needed to be a little less peaceful!$"

Route130_Text_SantiagoPostBattle: @ 82A3494
	.string "Swimming and battling like this…\n"
	.string "I'm one happy guy…$"

Route131_Text_RichardIntro: @ 82A34C8
	.string "The sea is teeming with Pokémon.\n"
	.string "It's not easy swimming, I tell you.$"

Route131_Text_RichardDefeat: @ 82A350D
	.string "Pokémon raised by Trainers are\n"
	.string "seriously tough…$"

Route131_Text_RichardPostBattle: @ 82A353D
	.string "Gasp… Gasp…\n"
	.string "I'm wiped out…\p"
	.string "The going's easy. It's the leaving\n"
	.string "that's the hard part.\p"
	.string "Will I have any energy left to make\n"
	.string "the return trip?$"

Route131_Text_HermanIntro: @ 82A35C6
	.string "The sea… The sea… The sea…\n"
	.string "The sea as far as these eyes can see!\l"
	.string "I'm sick and tired of the sea!$"

Route131_Text_HermanDefeat: @ 82A3626
	.string "Bleah!$"

Route131_Text_HermanPostBattle: @ 82A362D
	.string "Lately it feels like I've been battling\n"
	.string "nothing but Water-types…\p"
	.string "Where's the variety?$"

Route131_Text_SusieIntro: @ 82A367B
	.string "Hi, sweetie, wait!\n"
	.string "We should battle, you and I!$"

Route131_Text_SusieDefeat: @ 82A36AB
	.string "You're tough in spite of the way\n"
	.string "you look!$"

Route131_Text_SusiePostBattle: @ 82A36D6
	.string "What? Not all Ace Trainers are arrogant\n"
	.string "braggarts you know!$"

Route131_Text_KaraIntro: @ 82A3751
	.string "Why do men love bathing suits so much?\p"
	.string "They all ogle me!$"

Route131_Text_KaraDefeat: @ 82A378A
	.string "I'm out of my depth!$"

Route131_Text_KaraPostBattle: @ 82A379F
	.string "Maybe it's not my bathing suit that\n"
	.string "makes men look. It must be my beauty!$"

Route131_Text_ReliIntro: @ 82A37E9
	.string "Reli: We'll work together as siblings\n"
	.string "to take you on!$"

Route131_Text_ReliDefeat: @ 82A381F
	.string "Reli: We couldn't win even though we\n"
	.string "worked together…$"

Route131_Text_ReliPostBattle: @ 82A3855
	.string "Reli: The people of Pacifidlog are\n"
	.string "together with the sea and Pokémon from\l"
	.string "the time they are born.$"

Route131_Text_ReliNotEnoughMons: @ 82A38B7
	.string "Reli: You don't have two Pokémon?\n"
	.string "We can't enjoy a battle, then.$"

Route131_Text_IanIntro: @ 82A38F8
	.string "Ian: I'm doing my best together with\n"
	.string "my sis!$"

Route131_Text_IanDefeat: @ 82A3925
	.string "Ian: I did my best with my sis,\n"
	.string "but we still couldn't win…$"

Route131_Text_IanPostBattle: @ 82A3960
	.string "Ian: You know how Pacifidlog is\n"
	.string "a floating town?\p"
	.string "So, wherever there is the sea,\n"
	.string "that's a part of Pacifidlog!$"

Route131_Text_IanNotEnoughMons: @ 82A39CD
	.string "Ian: If you have two Pokémon,\n"
	.string "we'll take you on!$"

Route131_Text_TaliaIntro: @ 82A39FE
	.string "If you can beat me, I'll give you some\n"
	.string "great information!$"

Route131_Text_TaliaDefeat: @ 82A3A38
	.string "Oh?\n"
	.string "Did I lose?$"

Route131_Text_TaliaPostBattle: @ 82A3A48
	.string "There is an odd place nearby.\n"
	.string "There's a huge tower there.\l"
	.string "Why don't you go take a look?$"

Route131_Text_KevinIntro: @ 82A3AA0
	.string "The people of Pacifidlog are\n"
	.string "a peaceful bunch.\p"
	.string "They never get angry.\n"
	.string "That goes for me, too.$"

Route131_Text_KevinDefeat: @ 82A3AFC
	.string "Oops!$"

Route131_Text_KevinPostBattle: @ 82A3B02
	.string "Tch! …Oh, wait.\n"
	.string "I'm not angry. Honestly!\p"
	.string "But, boy, you're strong!\n"
	.string "Hahaha!$"

Route132_Text_GilbertIntro: @ 82A3B4C
	.string "I used to catch colds all the time as\n"
	.string "a kid, but I became totally fit after\l"
	.string "I started swimming.$"

Route132_Text_GilbertDefeat: @ 82A3BAC
	.string "I crave more power…$"

Route132_Text_GilbertPostBattle: @ 82A3BC0
	.string "Trainers travel the fields and\n"
	.string "mountains, so they must be fit, too.$"

Route132_Text_DanaIntro: @ 82A3C04
	.string "I try not to swim where the currents\n"
	.string "are too strong.$"

Route132_Text_DanaDefeat: @ 82A3C39
	.string "Oh, please, no!$"

Route132_Text_DanaPostBattle: @ 82A3C49
	.string "If I get swept away, I'll lose all my\n"
	.string "sense of place…$"

Route132_Text_RonaldIntro: @ 82A3C7F
	.string "Win or lose, you'll never know until\n"
	.string "you try!$"

Route132_Text_RonaldDefeat: @ 82A3CAD
	.string "Waah!\n"
	.string "I sank in defeat!$"

Route132_Text_RonaldPostBattle: @ 82A3CC5
	.string "I never battle when I know I'll win.\n"
	.string "I like to battle at the razor's edge of\l"
	.string "victory and defeat!$"

Route132_Text_KiyoIntro: @ 82A3D26
	.string "I contemplate Pokémon 24 hours a day.\n"
	.string "How could you possibly beat me?$"

Route132_Text_KiyoDefeat: @ 82A3D6C
	.string "I lose.\n"
	.string "I will concede defeat.$"

Route132_Text_KiyoPostBattle: @ 82A3D8B
	.string "Urggh…\n"
	.string "You're a Pokémon fanatic, aren't you?\p"
	.string "You must contemplate Pokémon 24 hours\n"
	.string "a day, don't you?$"

Route132_Text_MakaylaIntro: @ 82A3DF0
	.string "I'm always with my husband,\n"
	.string "but I can win even without him.$"

Route132_Text_MakaylaDefeat: @ 82A3E2C
	.string "Oh, I guess I wasn't good enough.$"

Route132_Text_MakaylaPostBattle: @ 82A3E4E
	.string "That young man over there looks just\n"
	.string "like my husband when he was young.\p"
	.string "He's making me blush!$"

Route132_Text_JonathanIntro: @ 82A3EAC
	.string "Someone's been watching me intently.\n"
	.string "Was it you?$"

Route132_Text_JonathanDefeat: @ 82A3EDD
	.string "Wow!\n"
	.string "That's pretty strong, all right!$"

Route132_Text_JonathanPostBattle: @ 82A3F03
	.string "I can't shake this feeling that\n"
	.string "someone's watching me.\p"
	.string "I can't concentrate!$"

Route132_Text_PaxtonIntro: @ 82A3F4F
	.string "Now where could my wife have gone?\n"
	.string "I'm always with her.\l"
	.string "I wonder if I can win on my own.$"

Route132_Text_PaxtonDefeat: @ 82A3FA8
	.string "Ah, I see that I couldn't manage\n"
	.string "to win on my own after all.$"

Route132_Text_PaxtonPostBattle: @ 82A3FE5
	.string "My wife must be looking for me.\n"
	.string "I'd best go find her right away.$"

Route132_Text_DarcyIntro: @ 82A4026
	.string "I liked training here by myself.\n"
	.string "It's awful that all these people came!$"

Route132_Text_DarcyDefeat: @ 82A406E
	.string "Okay! I won't complain about other\n"
	.string "people being here.$"

Route132_Text_DarcyPostBattle: @ 82A40A4
	.string "I suppose I can partner up with that\n"
	.string "old man and challenge that other team.$"

Route133_Text_FranklinIntro: @ 82A40F0
	.string "Did the currents carry you here, too?\n"
	.string "This must have been fated.\l"
	.string "Let's battle!$"

Route133_Text_FranklinDefeat: @ 82A413F
	.string "Strong!\n"
	.string "Too much so!$"

Route133_Text_FranklinPostBattle: @ 82A4154
	.string "It's just my luck that a tough Trainer\n"
	.string "like you would drift here…\l"
	.string "I must be cursed…$"

Route133_Text_DebraIntro: @ 82A41A8
	.string "I've led a life of woe and misery…\n"
	.string "I've been cast away, and this is where\l"
	.string "I've drifted…$"

Route133_Text_DebraDefeat: @ 82A4200
	.string "Another loss…$"

Route133_Text_DebraPostBattle: @ 82A420E
	.string "A life adrift…\n"
	.string "I don't want it anymore!$"

Route133_Text_LindaIntro: @ 82A4236
	.string "Welcome!\n"
	.string "I've been expecting you!$"

Route133_Text_LindaDefeat: @ 82A4258
	.string "No! Please!$"

Route133_Text_LindaPostBattle: @ 82A4264
	.string "A strong child Trainer…\n"
	.string "That's so annoying!$"

Route133_Text_WarrenIntro: @ 82A4290
	.string "I want to win like everyone else, but I\n"
	.string "won't raise Pokémon like everyone else.$"

Route133_Text_WarrenDefeat: @ 82A42E0
	.string "Darn it!\n"
	.string "My way is still too slack!$"

Route133_Text_WarrenPostBattle: @ 82A4304
	.string "It's way more fun to do things the way\n"
	.string "I want than to be like everybody else.\l"
	.string "I mean, that's obvious!$"

Route133_Text_BeckIntro: @ 82A436A
	.string "I came all the way out here with my\n"
	.string "Bird Pokémon.$"

Route133_Text_BeckDefeat: @ 82A439C
	.string "You…\n"
	.string "You're stunningly cool!$"

Route133_Text_BeckPostBattle: @ 82A43B9
	.string "I'd like to go back to Fortree,\n"
	.string "but I've grown to like this place, too.$"

Route133_Text_MollieIntro: @ 82A4401
	.string "I must have battled thousands\n"
	.string "of times. I've lost count.$"

Route133_Text_MollieDefeat: @ 82A443A
	.string "I may have lost thousands of times,\n"
	.string "but a loss still stings.$"

Route133_Text_MolliePostBattle: @ 82A4477
	.string "Keep at this, youngster. So you can\n"
	.string "become like my husband and me.$"

Route133_Text_ConorIntro: @ 82A44BA
	.string "Young people are too happy to go with\n"
	.string "the flow. They're without direction.$"

Route133_Text_ConorDefeat: @ 82A4505
	.string "You have a firm sense of purpose.$"

Route133_Text_ConorPostBattle: @ 82A4527
	.string "Don't let others lead you astray.\n"
	.string "Don't lose direction as you grow older.$"

Route134_Text_JackIntro: @ 82A4571
	.string "Even those Pokémon that can swim are\n"
	.string "carried along by the rapid currents.$"

Route134_Text_JackDefeat: @ 82A45BB
	.string "Aiyeeeeh!$"

Route134_Text_JackPostBattle: @ 82A45C5
	.string "I think Pokémon enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_LaurelIntro: @ 82A4609
	.string "My Luvdisc are looking for a fun\n"
	.string "match. Will you join us?$"

Route134_Text_LaurelDefeat: @ 82A4643
	.string "Oopsie!$"

Route134_Text_LaurelPostBattle: @ 82A464B
	.string "There's a collector who's after\n"
	.string "the scales of Luvdisc.$"

Route134_Text_AlexIntro: @ 82A4682
	.string "Okeydokey! That's enough rest, gang!\n"
	.string "It's time for a match!$"

Route134_Text_AlexDefeat: @ 82A46BE
	.string "Tuckered out again…$"

Route134_Text_AlexPostBattle: @ 82A46D2
	.string "My Bird Pokémon get tired quickly after\n"
	.string "a long flight…$"

Route134_Text_HitoshiIntro: @ 82A4709
	.string "You're a Pokémon Trainer.\n"
	.string "No need for words. We battle now.$"

Route134_Text_HitoshiDefeat: @ 82A4745
	.string "… … … … … …\n"
	.string "… … … … … …$"

Route134_Text_HitoshiPostBattle: @ 82A475D
	.string "It was I who challenged you, and yet\n"
	.string "I lost. I am deeply shamed…$"

Route134_Text_AaronIntro: @ 82A479E
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_AaronDefeat: @ 82A47E1
	.string "I willingly concede defeat.$"

Route134_Text_AaronPostBattle: @ 82A47FD
	.string "We will return for more training at\n"
	.string "Meteor Falls.\p"
	.string "If you'd like, you should go, too.\n"
	.string "It will definitely toughen you up!$"

Route134_Text_KelvinIntro: @ 82A4875
	.string "O-our boat!\n"
	.string "The tide carried it away!$"

Route134_Text_KelvinDefeat: @ 82A489B
	.string "Awawawawah!\n"
	.string "Please, stop! Please!$"

Route134_Text_KelvinPostBattle: @ 82A48BD
	.string "If we can't Surf, how are we supposed\n"
	.string "to get home?\p"
	.string "Actually, I know a fainted Pokémon\n"
	.string "can still Surf, but it feels wrong.$"

Route134_Text_MarleyIntro: @ 82A4937
	.string "Can your Pokémon dodge our\n"
	.string "lightning-quick attacks?$"

Route134_Text_MarleyDefeat: @ 82A496B
	.string "I never knew such a technique existed!\n"
	.string "You've defeated us thoroughly.$"

Route134_Text_MarleyPostBattle: @ 82A49B1
	.string "I haven't lost my passion for speed.\n"
	.string "I will try harder.$"

Route134_Text_ReynaIntro: @ 82A49E9
	.string "My Pokémon can't be taken down\n"
	.string "easily!$"

Route134_Text_ReynaDefeat: @ 82A4A10
	.string "You're kidding!\n"
	.string "Explain how I lost!$"

Route134_Text_ReynaPostBattle: @ 82A4A34
	.string "Haha!\n"
	.string "You won, all right!\p"
	.string "I'll work my way back up by taking on\n"
	.string "Trainers I happen to meet!$"

Route134_Text_HudsonIntro: @ 82A4A8F
	.string "Listen, have you seen another Sailor\n"
	.string "around here?$"

Route134_Text_HudsonDefeat: @ 82A4AC1
	.string "Now, that's something!$"

Route134_Text_HudsonPostBattle: @ 82A4AD8
	.string "Our boat drifted out to sea.\p"
	.string "My buddy's a timid fellow, so I'm\n"
	.string "worried about him.$"

AshenWoods_Text_AlannahIntro:
	.string "Don't tell Hong, but I actually\n"
	.string "like brown-haired Muirne…$"

AshenWoods_Text_AlannahDefeat:
	.string "I commissioned a few arts of her,\n"
	.string "so I'm kinda committed.$"

AshenWoods_Text_AlannahPostBattle:
	.string "I commissioned a few arts of her,\n"
	.string "so I'm kinda committed.$"
	
AshenWoods_Text_MartinIntro:
	.string "Everyone knows the best Sanaki is\n"
	.string "Growthnaki, and if you disagree,\l"
	.string "then you leave me no choice.$"

AshenWoods_Text_MartinDefeat:
	.string "…But the SR+ looks so much better…$"

AshenWoods_Text_MartinPostBattle:
	.string "…But the SR+ looks so much better…$"
	
AshenWoods_Text_RomanIntro:
	.string "Man, Roy is good, but I feel the\n"
	.string "call to return to Nino.$"

AshenWoods_Text_RomanDefeat:
	.string "Alright, time to spin a wheel and\n"
	.string "see what color I splash!$"

AshenWoods_Text_RomanPostBattle:
	.string "Alright, time to spin a wheel and\n"
	.string "see what color I splash!$"
	
AshenWoods_Text_ElmerIntro:
	.string "I remember the last time I bought boxes\n"
	.string "they were $40 each.$"

AshenWoods_Text_ElmerDefeat:
	.string "Now most of them are hundreds of dollars…$"

AshenWoods_Text_ElmerPostBattle:
	.string "Now most of them are hundreds of dollars…$"
